export const routes = {
  home: "/",
  jualAc: "/jual-ac",
  jualAcPurwokerto: "/jual-ac-purwokerto",
  jualAcBanyumas: "/jual-ac-banyumas",
  jualAcSokaraja: "/jual-ac-sokaraja",
  jualAcAjibarang: "/jual-ac-ajibarang",
  jualAcBaturraden: "/jual-ac-baturraden",
  jualAcYogyakarta: "/jual-ac-yogyakarta",
  jualAcSemarang: "/jual-ac-semarang",
  jualAcSolo: "/jual-ac-solo",
  jualAcPurbalingga: "/jual-ac-purbalingga",
  jualAcCilacap: "/jual-ac-cilacap",
  jualAcKebumen: "/jual-ac-kebumen",
  jualAcTegal: "/jual-ac-tegal",
  jualAcBanjarnegara: "/jual-ac-banjarnegara",

  katalog: "/katalog",
  katalogAcSetengahPk: "/katalog/ac-1-2-pk",
  katalogAcSatuPk: "/katalog/ac-1-pk",
  katalogAcSatuSetengahPk: "/katalog/ac-1-5-pk",
  katalogAcDuaPk: "/katalog/ac-2-pk",
  katalogAcSplitRumah: "/katalog/ac-split-rumah",
  katalogAcInverter: "/katalog/ac-inverter",
  katalogAcLowWatt: "/katalog/ac-low-watt",
  katalogAcKantorKomersial: "/katalog/ac-kantor-komersial",

  kalkulatorPkAc: "/kalkulator-pk-ac",
  gantiAcBaruPurwokerto: "/ganti-ac-baru-purwokerto",

  brandGree: "/brand/gree",
  brandDaikin: "/brand/daikin",
  brandMidea: "/brand/midea",
  brandHisense: "/brand/hisense",
  brandLainnya: "/brand/lainnya",
  brandSansui: "/brand/sansui",
  brandSharp: "/brand/sharp",
  brandSamsung: "/brand/samsung",
  brandPanasonic: "/brand/panasonic",
  brandAriston: "/brand/ariston",

  pengadaanAc: "/pengadaan-ac",
  pengadaanKostApartemen: "/pengadaan-ac/kost-apartemen-skala-besar",
  pengadaanHotelGuestHouse: "/pengadaan-ac/hotel-guest-house",
  pengadaanKontraktorDeveloper: "/pengadaan-ac/kontraktor-developer",
  pengadaanGedungKantorRuko: "/pengadaan-ac/gedung-kantor-ruko",
  pengadaanCafeResto: "/pengadaan-ac/cafe-resto",

  pengirimanPemasangan: "/pengiriman-pemasangan",
  buktiPengirimanProyek: "/bukti-pengiriman-proyek",
  tentangKami: "/tentang-kami",
  kontak: "/kontak",
  artikel: "/artikel",
  artikelPanduanBeliAcBaru: "/artikel/panduan-beli-ac-baru",
  artikelSharpBeyPurwokerto: "/artikel/sharp-bey-purwokerto",
  artikelAcSatuPkUntukRuanganBerapa: "/artikel/ac-1-pk-untuk-ruangan-berapa",
  artikelAcInverterVsLowWatt: "/artikel/ac-inverter-vs-low-watt",
  artikelAcKurangDingin: "/artikel/ac-kurang-dingin-belum-tentu-freon-habis",
  artikelPanduanInstalasiAcBaru: "/artikel/panduan-instalasi-ac-baru",
  artikelCaraMemilihAcKamarTigaKaliEmpat: "/artikel/cara-memilih-ac-untuk-kamar-3x4",
};

export const sitemapRoutes = [
  { path: routes.home, priority: 1.0 },
  { path: routes.jualAc, priority: 0.9 },
  { path: routes.jualAcPurwokerto, priority: 0.9 },
  { path: routes.jualAcBanyumas, priority: 0.85 },
  { path: routes.jualAcSokaraja, priority: 0.85 },
  { path: routes.jualAcAjibarang, priority: 0.78 },
  { path: routes.jualAcBaturraden, priority: 0.78 },
  { path: routes.jualAcYogyakarta, priority: 0.85 },
  { path: routes.jualAcSemarang, priority: 0.85 },
  { path: routes.jualAcSolo, priority: 0.85 },
  { path: routes.jualAcPurbalingga, priority: 0.8 },
  { path: routes.jualAcCilacap, priority: 0.8 },
  { path: routes.jualAcKebumen, priority: 0.8 },
  { path: routes.jualAcTegal, priority: 0.75 },
  { path: routes.jualAcBanjarnegara, priority: 0.75 },

  { path: routes.katalog, priority: 0.85 },
  { path: routes.kalkulatorPkAc, priority: 0.9 },
  { path: routes.gantiAcBaruPurwokerto, priority: 0.75 },
  { path: routes.katalogAcSetengahPk, priority: 0.75 },
  { path: routes.katalogAcSatuPk, priority: 0.78 },
  { path: routes.katalogAcSatuSetengahPk, priority: 0.78 },
  { path: routes.katalogAcDuaPk, priority: 0.78 },
  { path: routes.katalogAcSplitRumah, priority: 0.75 },
  { path: routes.katalogAcInverter, priority: 0.75 },
  { path: routes.katalogAcLowWatt, priority: 0.75 },
  { path: routes.katalogAcKantorKomersial, priority: 0.75 },

  { path: routes.brandGree, priority: 0.8 },
  { path: routes.brandDaikin, priority: 0.8 },
  { path: routes.brandMidea, priority: 0.8 },
  { path: routes.brandHisense, priority: 0.75 },
  { path: routes.brandLainnya, priority: 0.7 },
  { path: routes.brandSansui, priority: 0.7 },
  { path: routes.brandSharp, priority: 0.7 },
  { path: routes.brandSamsung, priority: 0.7 },
  { path: routes.brandPanasonic, priority: 0.7 },
  { path: routes.brandAriston, priority: 0.7 },

  { path: routes.pengadaanAc, priority: 0.85 },
  { path: routes.pengadaanKostApartemen, priority: 0.75 },
  { path: routes.pengadaanHotelGuestHouse, priority: 0.75 },
  { path: routes.pengadaanKontraktorDeveloper, priority: 0.75 },
  { path: routes.pengadaanGedungKantorRuko, priority: 0.75 },
  { path: routes.pengadaanCafeResto, priority: 0.75 },

  { path: routes.pengirimanPemasangan, priority: 0.7 },
  { path: routes.buktiPengirimanProyek, priority: 0.7 },
  { path: routes.tentangKami, priority: 0.65 },
  { path: routes.kontak, priority: 0.8 },
  { path: routes.artikel, priority: 0.6 },
  { path: routes.artikelPanduanBeliAcBaru, priority: 0.55 },
  { path: routes.artikelSharpBeyPurwokerto, priority: 0.5 },
  { path: routes.artikelAcSatuPkUntukRuanganBerapa, priority: 0.55 },
  { path: routes.artikelAcInverterVsLowWatt, priority: 0.55 },
  { path: routes.artikelAcKurangDingin, priority: 0.5 },
  { path: routes.artikelPanduanInstalasiAcBaru, priority: 0.5 },
  { path: routes.artikelCaraMemilihAcKamarTigaKaliEmpat, priority: 0.5 },
];
