export const routes = {
  home: "/",
  jualAc: "/jual-ac",
  jualAcPurwokerto: "/jual-ac-purwokerto",
  jualAcBanyumas: "/jual-ac-banyumas",
  jualAcJatilawang: "/jual-ac-jatilawang",
  jualAcCilongok: "/jual-ac-cilongok",
  jualAcSokaraja: "/jual-ac-sokaraja",
  jualAcAjibarang: "/jual-ac-ajibarang",
  jualAcBaturraden: "/jual-ac-baturraden",
  jualAcWangon: "/jual-ac-wangon",
  jualAcKaranglewas: "/jual-ac-karanglewas",
  jualAcKembaran: "/jual-ac-kembaran",
  jualAcPatikraja: "/jual-ac-patikraja",
  jualAcRawalo: "/jual-ac-rawalo",
  jualAcYogyakarta: "/jual-ac-yogyakarta",
  jualAcSemarang: "/jual-ac-semarang",
  jualAcSolo: "/jual-ac-solo",
  jualAcPurbalingga: "/jual-ac-purbalingga",
  jualAcCilacap: "/jual-ac-cilacap",
  jualAcKroya: "/jual-ac-kroya",
  jualAcMajenang: "/jual-ac-majenang",
  jualAcSidareja: "/jual-ac-sidareja",
  jualAcKesugihan: "/jual-ac-kesugihan",
  jualAcAdipala: "/jual-ac-adipala",
  jualAcKebumen: "/jual-ac-kebumen",
  jualAcGombong: "/jual-ac-gombong",
  jualAcKaranganyarKebumen: "/jual-ac-karanganyar-kebumen",
  jualAcKutowinangun: "/jual-ac-kutowinangun",
  jualAcTegal: "/jual-ac-tegal",
  jualAcBanjarnegara: "/jual-ac-banjarnegara",
  jualAcSumbang: "/jual-ac-sumbang",
  jualAcKedungbanteng: "/jual-ac-kedungbanteng",
  jualAcKalibagor: "/jual-ac-kalibagor",
  jualAcMagelang: "/jual-ac-magelang",
  jualAcPekalongan: "/jual-ac-pekalongan",
  jualAcSalatiga: "/jual-ac-salatiga",

  katalog: "/katalog",
  katalogAcSetengahPk: "/katalog/ac-1-2-pk",
  katalogAcSatuPk: "/katalog/ac-1-pk",
  katalogAcSatuSetengahPk: "/katalog/ac-1-5-pk",
  katalogAcDuaPk: "/katalog/ac-2-pk",
  katalogAcSplitRumah: "/katalog/ac-split-rumah",
  katalogAcInverter: "/katalog/ac-inverter",
  katalogAcLowWatt: "/katalog/ac-low-watt",
  katalogAcKantorKomersial: "/katalog/ac-kantor-komersial",

  kalkulatorPkAc: "/kalkulator-pk-ac",
  gantiAcBaruPurwokerto: "/ganti-ac-baru-purwokerto",

  brandGree: "/brand/gree",
  brandDaikin: "/brand/daikin",
  brandMidea: "/brand/midea",
  brandHisense: "/brand/hisense",
  brandLainnya: "/brand/lainnya",
  brandSansui: "/brand/sansui",
  brandSharp: "/brand/sharp",
  brandSamsung: "/brand/samsung",
  brandPanasonic: "/brand/panasonic",
  brandAriston: "/brand/ariston",

  pengadaanAc: "/pengadaan-ac",
  pengadaanKostApartemen: "/pengadaan-ac/kost-apartemen-skala-besar",
  pengadaanHotelGuestHouse: "/pengadaan-ac/hotel-guest-house",
  pengadaanKontraktorDeveloper: "/pengadaan-ac/kontraktor-developer",
  pengadaanGedungKantorRuko: "/pengadaan-ac/gedung-kantor-ruko",
  pengadaanCafeResto: "/pengadaan-ac/cafe-resto",

  pengirimanPemasangan: "/pengiriman-pemasangan",
  buktiPengirimanProyek: "/bukti-pengiriman-proyek",
  tentangKami: "/tentang-kami",
  kontak: "/kontak",
  artikel: "/artikel",
  artikelPanduanBeliAcBaru: "/artikel/panduan-beli-ac-baru",
  artikelSharpBeyPurwokerto: "/artikel/sharp-bey-purwokerto",
  artikelAcSatuPkUntukRuanganBerapa: "/artikel/ac-1-pk-untuk-ruangan-berapa",
  artikelAcInverterVsLowWatt: "/artikel/ac-inverter-vs-low-watt",
  artikelAcKurangDingin: "/artikel/ac-kurang-dingin-belum-tentu-freon-habis",
  artikelPanduanInstalasiAcBaru: "/artikel/panduan-instalasi-ac-baru",
  artikelCaraMemilihAcKamarTigaKaliEmpat: "/artikel/cara-memilih-ac-untuk-kamar-3x4",
  artikelAcBagusMerkApa: "/artikel/ac-bagus-merk-apa",
  artikelAcPalingHematListrik: "/artikel/ac-paling-hemat-listrik",
  artikelRekomendasiAcKamarTidur: "/artikel/rekomendasi-ac-kamar-tidur",
  artikelAcUntukListrik900Watt: "/artikel/ac-untuk-listrik-900-watt",
  artikelBiayaPasangAcBaru: "/artikel/biaya-pasang-ac-baru",
  artikelPilihanAcSetengahPkTerbaik: "/artikel/pilihan-ac-1-2-pk-terbaik",
  artikelBiayaServisVsGantiBaru: "/artikel/biaya-servis-ac-vs-ganti-baru",
  artikelTandaAcHarusGantiUnit: "/artikel/tanda-ac-harus-ganti-unit",
  artikelAcBorosListrikGantiInverter: "/artikel/ac-boros-listrik-ganti-inverter",
  // 12 artikel baru untuk topical authority
  artikelGreeVsDaikinUntukRumah: "/artikel/gree-vs-daikin-untuk-rumah",
  artikelMideaVsHisenseBudgetTerbatas: "/artikel/midea-vs-hisense-budget-terbatas",
  artikelDaikinVsPanasonicJangkaPanjang: "/artikel/daikin-vs-panasonic-jangka-panjang",
  artikelAcGreeCocokUntukSiapa: "/artikel/ac-gree-cocok-untuk-siapa",
  artikelCaraMenghitungKebutuhanAcKost: "/artikel/cara-menghitung-kebutuhan-ac-kost",
  artikelChecklistPengadaanAcHotel: "/artikel/checklist-pengadaan-ac-hotel",
  artikelPanduanBoqAcKontraktor: "/artikel/panduan-boq-ac-kontraktor",
  artikelAcUntukTokoRukoPilihPkBerapa: "/artikel/ac-untuk-toko-dan-ruko-pilih-pk-berapa",
  artikelAcKantorKecilInverterAtauLowWatt: "/artikel/ac-kantor-kecil-inverter-atau-low-watt",
  artikelAcUntukKosMahasiswaPurwokerto: "/artikel/ac-untuk-kos-mahasiswa-purwokerto",
  artikelAcUntukVillaPenginapanBaturraden: "/artikel/ac-untuk-villa-dan-penginapan-baturraden",
  artikelMemilihAcUntukDaerahPesisir: "/artikel/memilih-ac-untuk-daerah-pesisir",
};

export const sitemapRoutes = [
  { path: routes.home, priority: 1.0, lastModified: "2026-06-15" },
  { path: routes.jualAc, priority: 0.9, lastModified: "2026-06-02" },
  { path: routes.jualAcPurwokerto, priority: 0.9, lastModified: "2026-06-13" },
  { path: routes.jualAcBanyumas, priority: 0.85, lastModified: "2026-06-13" },
  { path: routes.jualAcJatilawang, priority: 0.7, lastModified: "2026-06-13" },
  { path: routes.jualAcCilongok, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.jualAcSokaraja, priority: 0.85, lastModified: "2026-06-13" },
  { path: routes.jualAcAjibarang, priority: 0.78, lastModified: "2026-06-13" },
  { path: routes.jualAcBaturraden, priority: 0.78, lastModified: "2026-06-13" },
  { path: routes.jualAcWangon, priority: 0.76, lastModified: "2026-06-13" },
  { path: routes.jualAcKaranglewas, priority: 0.76, lastModified: "2026-06-13" },
  { path: routes.jualAcKembaran, priority: 0.76, lastModified: "2026-06-13" },
  { path: routes.jualAcPatikraja, priority: 0.74, lastModified: "2026-06-13" },
  { path: routes.jualAcRawalo, priority: 0.74, lastModified: "2026-06-13" },
  { path: routes.jualAcYogyakarta, priority: 0.85, lastModified: "2026-06-11" },
  { path: routes.jualAcSemarang, priority: 0.85, lastModified: "2026-06-11" },
  { path: routes.jualAcSolo, priority: 0.85, lastModified: "2026-06-11" },
  { path: routes.jualAcPurbalingga, priority: 0.8, lastModified: "2026-06-15" },
  { path: routes.jualAcCilacap, priority: 0.8, lastModified: "2026-06-13" },
  { path: routes.jualAcKroya, priority: 0.7, lastModified: "2026-06-13" },
  { path: routes.jualAcMajenang, priority: 0.7, lastModified: "2026-06-13" },
  { path: routes.jualAcSidareja, priority: 0.7, lastModified: "2026-06-13" },
  { path: routes.jualAcKesugihan, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.jualAcAdipala, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.jualAcKebumen, priority: 0.8, lastModified: "2026-06-13" },
  { path: routes.jualAcGombong, priority: 0.65, lastModified: "2026-06-13" },
  { path: routes.jualAcKaranganyarKebumen, priority: 0.65, lastModified: "2026-06-13" },
  { path: routes.jualAcKutowinangun, priority: 0.65, lastModified: "2026-06-13" },
  { path: routes.jualAcTegal, priority: 0.75, lastModified: "2026-06-13" },
  { path: routes.jualAcBanjarnegara, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.jualAcSumbang, priority: 0.65, lastModified: "2026-06-15" },
  { path: routes.jualAcKedungbanteng, priority: 0.65, lastModified: "2026-06-15" },
  { path: routes.jualAcKalibagor, priority: 0.65, lastModified: "2026-06-15" },
  { path: routes.jualAcMagelang, priority: 0.75, lastModified: "2026-06-10" },
  { path: routes.jualAcPekalongan, priority: 0.72, lastModified: "2026-06-10" },
  { path: routes.jualAcSalatiga, priority: 0.7, lastModified: "2026-06-10" },

  { path: routes.katalog, priority: 0.85, lastModified: "2026-06-15" },
  { path: routes.kalkulatorPkAc, priority: 0.9, lastModified: "2026-06-15" },
  { path: routes.gantiAcBaruPurwokerto, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.katalogAcSetengahPk, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.katalogAcSatuPk, priority: 0.78, lastModified: "2026-06-15" },
  { path: routes.katalogAcSatuSetengahPk, priority: 0.78, lastModified: "2026-06-15" },
  { path: routes.katalogAcDuaPk, priority: 0.78, lastModified: "2026-06-15" },
  { path: routes.katalogAcSplitRumah, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.katalogAcInverter, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.katalogAcLowWatt, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.katalogAcKantorKomersial, priority: 0.75, lastModified: "2026-06-15" },

  { path: routes.brandGree, priority: 0.8, lastModified: "2026-06-15" },
  { path: routes.brandDaikin, priority: 0.8, lastModified: "2026-06-15" },
  { path: routes.brandMidea, priority: 0.8, lastModified: "2026-06-15" },
  { path: routes.brandHisense, priority: 0.75, lastModified: "2026-06-15" },
  { path: routes.brandLainnya, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.brandSansui, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.brandSharp, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.brandSamsung, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.brandPanasonic, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.brandAriston, priority: 0.7, lastModified: "2026-06-15" },

  { path: routes.pengadaanAc, priority: 0.85, lastModified: "2026-06-13" },
  { path: routes.pengadaanKostApartemen, priority: 0.75, lastModified: "2026-06-13" },
  { path: routes.pengadaanHotelGuestHouse, priority: 0.8, lastModified: "2026-06-13" },
  { path: routes.pengadaanKontraktorDeveloper, priority: 0.8, lastModified: "2026-06-13" },
  { path: routes.pengadaanGedungKantorRuko, priority: 0.75, lastModified: "2026-06-13" },
  { path: routes.pengadaanCafeResto, priority: 0.75, lastModified: "2026-06-13" },

  { path: routes.pengirimanPemasangan, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.buktiPengirimanProyek, priority: 0.7, lastModified: "2026-06-15" },
  { path: routes.tentangKami, priority: 0.65, lastModified: "2026-06-15" },
  { path: routes.kontak, priority: 0.8, lastModified: "2026-06-15" },
  { path: routes.artikel, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelPanduanBeliAcBaru, priority: 0.55, lastModified: "2026-06-18" },
  { path: routes.artikelSharpBeyPurwokerto, priority: 0.5, lastModified: "2026-06-01" },
  { path: routes.artikelAcSatuPkUntukRuanganBerapa, priority: 0.55, lastModified: "2026-06-18" },
  { path: routes.artikelAcInverterVsLowWatt, priority: 0.55, lastModified: "2026-06-11" },
  { path: routes.artikelAcKurangDingin, priority: 0.5, lastModified: "2026-06-11" },
  { path: routes.artikelPanduanInstalasiAcBaru, priority: 0.5, lastModified: "2026-06-01" },
  { path: routes.artikelCaraMemilihAcKamarTigaKaliEmpat, priority: 0.5, lastModified: "2026-06-18" },
  { path: routes.artikelAcBagusMerkApa, priority: 0.55, lastModified: "2026-06-18" },
  { path: routes.artikelAcPalingHematListrik, priority: 0.55, lastModified: "2026-06-11" },
  { path: routes.artikelRekomendasiAcKamarTidur, priority: 0.55, lastModified: "2026-06-18" },
  { path: routes.artikelAcUntukListrik900Watt, priority: 0.55, lastModified: "2026-06-18" },
  { path: routes.artikelBiayaPasangAcBaru, priority: 0.55, lastModified: "2026-06-11" },
  { path: routes.artikelPilihanAcSetengahPkTerbaik, priority: 0.55, lastModified: "2026-06-11" },
  { path: routes.artikelBiayaServisVsGantiBaru, priority: 0.6, lastModified: "2026-06-13" },
  { path: routes.artikelTandaAcHarusGantiUnit, priority: 0.6, lastModified: "2026-06-13" },
  { path: routes.artikelAcBorosListrikGantiInverter, priority: 0.6, lastModified: "2026-06-13" },
  // 12 artikel baru untuk topical authority
  { path: routes.artikelGreeVsDaikinUntukRumah, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelMideaVsHisenseBudgetTerbatas, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelDaikinVsPanasonicJangkaPanjang, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelAcGreeCocokUntukSiapa, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelCaraMenghitungKebutuhanAcKost, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelChecklistPengadaanAcHotel, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelPanduanBoqAcKontraktor, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelAcUntukTokoRukoPilihPkBerapa, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelAcKantorKecilInverterAtauLowWatt, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelAcUntukKosMahasiswaPurwokerto, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelAcUntukVillaPenginapanBaturraden, priority: 0.6, lastModified: "2026-06-15" },
  { path: routes.artikelMemilihAcUntukDaerahPesisir, priority: 0.6, lastModified: "2026-06-15" },
];
