import { routes } from "@/content/routes";

export const banyumasAreas = [
  {
      slug: "jual-ac-purwokerto",
      path: routes.jualAcPurwokerto,
      areaName: "Purwokerto",
      localLandmarks: [
        "Kampus UNSOED (Universitas Jenderal Soedirman)",
        "Alun-alun Purwokerto",
        "Stasiun Purwokerto",
        "Terminal Bulupitu",
        "RSUD Prof. Dr. Margono Soekarjo",
      ],
      localBenefits: [
        "Kos mahasiswa di sekitar UNSOED butuh banyak unit hemat daya dengan tipe seragam",
        "Hotel, guest house, ruko, dan kantor di pusat kota perlu kapasitas untuk ruang publik dan pemakaian panjang",
        "Pusat perdagangan yang padat dan panas membutuhkan PK yang dihitung dari luas dan lalu lalang pengunjung",
      ],
      localCases: [
        ["Kos & rumah sewa sekitar UNSOED", "Banyak unit hemat daya dengan tipe seragam untuk hunian mahasiswa."],
        ["Hotel, guest house & perkantoran", "AC ruang publik dan kamar dengan pemakaian harian panjang di pusat kota."],
        ["Toko, ruko & pusat perdagangan", "AC area pelanggan yang ramai dengan kapasitas sesuai luas dan pengunjung."],
      ],
      localFaq: [
        [
          "Berapa unit AC untuk kos banyak kamar dekat UNSOED?",
          "Tergantung jumlah kamar dan daya listrik total bangunan. Kirim jumlah kamar dan daya — tim Radja AC langsung cek pilihan unit hemat daya dengan tipe seragam biar perawatannya gampang.",
        ],
        [
          "AC untuk hotel, guest house, atau kantor di pusat kota Purwokerto?",
          "Bisa. Kirim jumlah ruang atau kamar, ukuran, jam pemakaian, dan preferensi brand — tim siapkan kapasitas dan pilihan untuk ruang publik yang dipakai seharian.",
        ],
        [
          "AC untuk toko atau ruko di pusat perdagangan Purwokerto?",
          "Ditentukan dari luas, jumlah pengunjung, dan pintu yang sering terbuka. Kirim ukuran ruang usaha untuk perkiraan PK yang pas.",
        ],
        [
          "AC lama di rumah atau kost Purwokerto sudah tidak dingin, ganti atau servis?",
          "Kalau unit sudah lebih dari 5 tahun, sering kurang dingin, dan listrik terasa boros — lebih hemat ganti baru. Biaya servis berulang bisa melebihi harga unit baru dalam setahun. Kirim kondisi unit lama dan ukuran ruangan, tim bantu hitung mana yang lebih masuk akal.",
        ],
        [
          "Harga pasang AC di Purwokerto berapa?",
          "Tergantung panjang pipa, posisi outdoor, dan kondisi lokasi. Kirim foto titik indoor dan outdoor — tim Radja AC kasih estimasi biaya pasang yang jelas sebelum kamu putuskan.",
        ],
      ],
      label: "Jual AC Purwokerto",
      title: "Jual AC Purwokerto | Showroom Ready Stok, Cek PK & Pasang Hari Ini",
      description:
        "Beli AC di Purwokerto untuk rumah, kost UNSOED, toko, kantor, atau banyak unit? Radja AC cek PK, stok, harga, dan jadwal pasang langsung via WhatsApp.",
      h1: "Jual AC Purwokerto — stok dicek hari ini, pasang bisa dijadwalkan",
      eyebrow: "Area Utama Purwokerto",
      intro:
        "Butuh beli AC di Purwokerto untuk rumah, kost, toko, kantor, hotel, guest house, hospitality, atau banyak unit? Mulai dari cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
      localContext:
        "Purwokerto adalah pusat kota dan kawasan kampus Banyumas: ada kampus UNSOED dengan ribuan kos mahasiswa, pusat perdagangan, hotel, ruko, dan perkantoran. Permintaan AC datang dari kos dan rumah sewa di sekitar kampus, hotel dan guest house, toko serta ruko di pusat perdagangan, dan kantor yang beroperasi seharian. Karena beban panas tiap ruang berbeda, tim Radja AC mengecek ukuran ruangan, daya listrik, jam pemakaian, jumlah unit, dan alamat sebelum menentukan unit.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk kebutuhan Purwokerto, stok unit, jadwal pengiriman, opsi pemasangan, dan kebutuhan material dikonfirmasi berdasarkan alamat serta kondisi lokasi.",
      commonNeeds: [
        "AC kamar tidur, rumah tinggal, dan ruang keluarga di Purwokerto",
        "AC kost, kontrakan, homestay, dan kamar sewa",
        "AC toko, ruko, kantor, klinik, dan ruang usaha",
        "Pengadaan beberapa unit untuk usaha, hotel, guest house, kantor, proyek, dan kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Ukuran ruangan, tinggi plafon, dan arah panas matahari",
        "Daya listrik dan kebutuhan standard, low watt, atau inverter",
        "Jumlah unit, preferensi brand, dan target anggaran",
        "Alamat Purwokerto, kebutuhan unit saja, pengiriman, atau opsi pemasangan",
      ],
      paymentNote:
        "Pembayaran fleksibel bisa dikonsultasikan: DP, COD, atau transfer setelah kebutuhan unit, pengiriman, dan opsi pemasangan jelas.",
      relatedLinks: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Sokaraja", routes.jualAcSokaraja],
        ["Katalog AC", routes.katalog],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["AC Split Rumah", routes.katalogAcSplitRumah],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["AC Inverter", routes.katalogAcInverter],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Purwokerto",
      waIntent: "cek stok AC Purwokerto dengan data ukuran ruangan daya listrik jumlah unit alamat dan kebutuhan pemasangan",
      waArea: "Purwokerto",
      keywordVariants: [
        "jual AC Purwokerto",
        "toko AC Purwokerto",
        "beli AC Purwokerto",
        "dealer AC Purwokerto",
        "AC rumah Purwokerto",
        "AC kost UNSOED Purwokerto",
        "AC toko Purwokerto",
        "pasang AC Purwokerto",
        "ganti AC lama Purwokerto",
        "AC inverter hemat listrik Purwokerto",
        "AC low watt 900 watt Purwokerto",
        "harga pasang AC Purwokerto",
      ],
      nearbyAreaLinks: [
        ["Banyumas", routes.jualAcBanyumas],
        ["Sokaraja", routes.jualAcSokaraja],
        ["Baturraden", routes.jualAcBaturraden],
        ["Kembaran", routes.jualAcKembaran],
      ],
      trustBullets: [
        "Purwokerto dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
        "Kebutuhan AC dicek dari ukuran ruangan, daya listrik, jumlah unit, stok aktif, dan opsi pemasangan.",
        "Pembeli bisa melihat bukti aktivitas Radja AC melalui dokumentasi showroom, stok fisik, pengiriman, dan pemasangan.",
      ],
    },
  {
      slug: "jual-ac-banyumas",
      path: routes.jualAcBanyumas,
      areaName: "Banyumas",
      localLandmarks: [
        "Kota lama Banyumas (alun-alun lama)",
        "Museum Wayang Banyumas",
        "Masjid Agung Nur Sulaiman",
        "Pasar Banyumas",
        "Dekat showroom dan gudang Radja AC di Pamijen, Sokaraja",
      ],
      localBenefits: [
        "Paling dekat dengan gudang Radja AC di Sokaraja, jadi pengiriman unit dan survei lokasi paling cepat dijadwalkan",
        "Toko, ruko, dan kantor instansi di pusat kota lama butuh ruang yang adem buat tamu dan staf",
        "Sebagian bangunan lama bersejarah perlu cek daya dan jalur pipa yang rapi sebelum pasang",
      ],
      localCases: [
        ["Rumah & bangunan lama", "Pemasangan AC kamar dengan jalur pipa rapi; bangunan tua dicek dayanya dulu."],
        ["Toko, ruko & kantor instansi", "AC ruang pelanggan dan ruang kerja di pusat kota lama Banyumas."],
        ["Banyak unit dekat gudang", "Pembelian beberapa unit yang pengiriman dan pemasangannya cepat karena dekat basis."],
      ],
      label: "Jual AC Banyumas",
      title: "Jual AC Banyumas | Cek Stok, PK, Pengiriman & Pemasangan — Radja AC",
      description:
        "Butuh AC area Banyumas untuk rumah, kost, toko, kantor, usaha, atau banyak unit? Radja AC cek PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
      h1: "Jual AC Banyumas untuk rumah, kost, toko, usaha, dan banyak unit",
      eyebrow: "Area Utama Banyumas",
      intro:
        "Radja AC melayani kebutuhan AC area Banyumas untuk rumah, kost, kontrakan, toko, kantor atau ruko, usaha, dan banyak unit. Sebelum pembelian, tim Radja AC mengecek kebutuhan PK, daya listrik, pilihan brand, stok, pengiriman, dan opsi pemasangan.",
      localContext:
        "Banyumas adalah kota lama bersejarah sekaligus area paling dekat dengan basis Radja AC—showroom dan gudang ada di Pamijen, Sokaraja. Pembeli AC di sini banyak dari rumah tinggal, toko dan ruko di pusat kota lama, kantor instansi, serta klinik. Karena dekat gudang, pengiriman unit dan survei lokasi paling cepat dijadwalkan di area ini. Untuk jual AC Banyumas, banyak yang ambil sekalian pemasangan, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      coverageNote:
        "Untuk alamat di area Banyumas, stok unit, pengiriman, jadwal, dan opsi pemasangan tetap dikonfirmasi berdasarkan lokasi detail, jumlah unit, akses pemasangan, dan ketersediaan tim.",
      commonNeeds: [
        "AC rumah, kamar tidur, dan ruang keluarga di Banyumas",
        "AC kost, kontrakan, homestay, dan rumah sewa",
        "AC toko, klinik, kantor, ruko, dan ruang usaha",
        "Pembelian beberapa unit untuk usaha lokal, properti sewa, proyek, pengadaan, atau kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Area detail di Banyumas dan akses lokasi",
        "Ukuran ruangan, tinggi plafon, dan kondisi panas matahari",
        "Daya listrik dan kebutuhan standard, low watt, atau inverter",
        "Jumlah unit, preferensi brand, anggaran, dan kebutuhan pemasangan",
      ],
      paymentNote:
        "Pembayaran fleksibel bisa dikonsultasikan: DP, COD, atau transfer setelah kebutuhan unit, pengiriman, dan opsi pemasangan jelas.",
      relatedLinks: [
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Sokaraja", routes.jualAcSokaraja],
        ["Katalog AC", routes.katalog],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["AC Split Rumah", routes.katalogAcSplitRumah],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["AC Gree", routes.brandGree],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Banyumas",
      waIntent: "cek stok AC Banyumas dengan data ukuran ruangan daya listrik jumlah unit alamat dan kebutuhan pemasangan",
      waArea: "Banyumas",
      keywordVariants: [
        "jual AC Banyumas",
        "toko AC Banyumas",
        "beli AC Banyumas",
        "AC rumah Banyumas",
        "AC kost Banyumas",
        "AC toko Banyumas",
        "pengiriman AC Banyumas",
        "pemasangan AC Banyumas",
      ],
      nearbyAreaLinks: [
        ["Purwokerto", routes.jualAcPurwokerto],
        ["Sokaraja", routes.jualAcSokaraja],
        ["Patikraja", routes.jualAcPatikraja],
        ["Rawalo", routes.jualAcRawalo],
      ],
      trustBullets: [
        "Banyumas adalah basis operasional Radja AC dengan showroom dan gudang di Pamijen, Sokaraja.",
        "Kebutuhan AC dicek dari area detail, ukuran ruangan, daya listrik, jumlah unit, stok aktif, dan opsi pemasangan.",
        "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi showroom, stok fisik, pengiriman, dan pemasangan.",
      ],
      localFaq: [
        [
          "Karena dekat gudang Sokaraja, pengiriman ke Banyumas cepat?",
          "Banyumas paling dekat dengan showroom dan gudang Radja AC di Pamijen, Sokaraja, jadi pengiriman unit dan survei lokasi biasanya paling cepat dijadwalkan. Sebutkan alamat dan jumlah unit.",
        ],
        [
          "Bangunan lama di kota Banyumas, aman pasang AC dan pipanya rapi?",
          "Bangunan tua sebaiknya dicek daya listrik dan jalur pipanya dulu agar instalasi rapi dan aman. Kirim foto titik indoor-outdoor untuk perkiraan.",
        ],
        [
          "Bisa lihat unit dulu di showroom sebelum beli untuk Banyumas?",
          "Bisa. Showroom dan gudang ada di Pamijen, Sokaraja; cek stok dan tipe unit dulu lewat WhatsApp agar tidak bolak-balik.",
        ],
        [
          "Beli beberapa unit untuk toko atau kantor di Banyumas, bagaimana?",
          "Sebutkan jumlah ruang dan ukurannya; unit dikirim cepat karena dekat gudang, lalu pemasangan dijadwalkan, dengan pembayaran DP atau transfer setelah stok dipastikan.",
        ],
      ],
    },
  {
      slug: "jual-ac-sokaraja",
      path: routes.jualAcSokaraja,
      areaName: "Sokaraja",
      localLandmarks: [
        "Sentra Getuk Goreng Sokaraja",
        "Jalan nasional Sokaraja (Purwokerto–Purbalingga)",
        "Pasar Sokaraja",
        "Showroom dan gudang Radja AC di Pamijen",
        "Deretan toko oleh-oleh dan rumah makan",
      ],
      localBenefits: [
        "Lokasi showroom dan gudang, jadi pembeli bisa datang langsung cek unit lalu pasang di hari yang sama",
        "Toko oleh-oleh dan rumah makan di jalur kuliner butuh ruang yang adem buat pembeli yang singgah",
        "Stok bisa dicek langsung sehingga pengiriman dan pemasangan paling cepat di area ini",
      ],
      localCases: [
        ["Toko oleh-oleh & rumah makan", "AC ruang pelanggan di jalur getuk goreng agar pengunjung betah memilih dan makan."],
        ["Ruko & rumah warga", "Pemasangan AC kamar dan ruang usaha dengan unit yang bisa diambil langsung dari gudang."],
        ["Datang langsung ke showroom", "Pembeli cek tipe dan stok di Pamijen lalu lanjut pasang di hari yang sama."],
      ],
      label: "Jual AC Sokaraja",
      title: "Jual AC Sokaraja | Dekat Showroom & Gudang Radja AC — Radja AC",
      description:
        "Butuh AC di Sokaraja dekat showroom dan gudang Radja AC? Cek stok, kebutuhan PK, pengiriman unit, opsi pemasangan, atau kebutuhan banyak unit via WhatsApp.",
      h1: "Jual AC Sokaraja dekat showroom dan gudang Radja AC",
      eyebrow: "Area Showroom & Gudang Radja AC",
      intro:
        "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Pembelian AC original untuk rumah, kost, toko, kantor, usaha, dan kebutuhan banyak unit bisa dimulai dari cek PK, stok, pengiriman, dan opsi pemasangan.",
      localContext:
        "Sokaraja adalah koridor kuliner dan dagang yang terkenal dengan getuk goreng, dilalui jalan nasional Purwokerto–Purbalingga—dan di Pamijen, Sokaraja inilah showroom serta gudang Radja AC berada. Pembeli AC banyak dari toko oleh-oleh dan rumah makan di sepanjang jalan, ruko, serta rumah warga. Karena ini lokasi gudang, pembeli sering datang langsung cek unit lalu pasang di hari yang sama. Untuk jual AC Sokaraja, pembayaran bisa DP, COD, atau transfer, dengan stok yang bisa dicek langsung.",
      coverageNote:
        "Untuk Sokaraja, Pamijen, dan area sekitar, tim Radja AC mengecek stok, alamat, jadwal, kebutuhan material, akses lokasi, dan opsi pemasangan agar estimasi lebih rapi sejak awal.",
      commonNeeds: [
        "AC rumah, kamar tidur, dan ruang keluarga di Sokaraja",
        "AC kost, kontrakan, homestay, dan rumah sewa",
        "AC toko, ruko, kantor, klinik, dan ruang usaha",
        "Kebutuhan AC banyak unit untuk usaha lokal, properti, proyek, atau pengadaan",
      ],
      buyingChecks: [
        "Alamat detail Sokaraja, Pamijen, atau area sekitar",
        "Ukuran ruangan, tinggi plafon, dan kondisi panas matahari",
        "Daya listrik dan kebutuhan standard, low watt, atau inverter",
        "Jumlah unit, preferensi brand, anggaran, dan kebutuhan pemasangan",
      ],
      paymentNote:
        "Pembayaran fleksibel bisa dikonsultasikan: DP, COD, atau transfer setelah kebutuhan unit, pengiriman, dan opsi pemasangan jelas.",
      relatedLinks: [
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Katalog AC", routes.katalog],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["AC Gree", routes.brandGree],
        ["AC Daikin", routes.brandDaikin],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Tentang Radja AC", routes.tentangKami],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Sokaraja",
      waIntent: "cek stok AC Sokaraja dengan data ukuran ruangan daya listrik jumlah unit alamat dan kebutuhan pemasangan",
      waArea: "Sokaraja",
      keywordVariants: [
        "jual AC Sokaraja",
        "toko AC Sokaraja",
        "beli AC Sokaraja",
        "showroom AC Sokaraja",
        "AC rumah Sokaraja",
        "AC toko Sokaraja",
        "pengiriman AC Sokaraja",
        "pemasangan AC Sokaraja",
      ],
      nearbyAreaLinks: [
        ["Purwokerto", routes.jualAcPurwokerto],
        ["Banyumas", routes.jualAcBanyumas],
        ["Kembaran", routes.jualAcKembaran],
        ["Patikraja", routes.jualAcPatikraja],
      ],
      trustBullets: [
        "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas.",
        "Pembeli bisa cek stok dan tipe unit terlebih dahulu sebelum datang atau melanjutkan pembelian.",
        "Kebutuhan AC dicek dari ukuran ruangan, daya listrik, jumlah unit, stok aktif, dan opsi pemasangan.",
      ],
      localFaq: [
        [
          "Showroom dan gudang Radja AC memang di Sokaraja?",
          "Ya, di Pamijen, Sokaraja. Pembeli area Sokaraja bisa datang langsung cek tipe dan stok unit, lalu lanjut pengiriman dan pemasangan—sering bisa di hari yang sama.",
        ],
        [
          "AC untuk toko oleh-oleh atau rumah makan di jalur Sokaraja, pilih apa?",
          "Ruang yang ramai dan pintunya sering kebuka butuh kapasitas sesuai luas dan jumlah pengunjung. Sebutkan ukuran ruang dan jam ramai untuk cek unit.",
        ],
        [
          "Karena dekat gudang, pasang AC di Sokaraja bisa cepat?",
          "Bisa. Stok dicek langsung di gudang Pamijen, jadi pengiriman dan pemasangan biasanya paling cepat dijadwalkan di area ini.",
        ],
        [
          "Pembayaran AC di Sokaraja bisa DP atau transfer?",
          "Bisa. Pembeli bisa DP dulu lalu pelunasan transfer atau COD; karena dekat gudang, stok dan unit gampang dipastikan sebelum bayar.",
        ],
      ],
    },
  {
        slug: "jual-ac-jatilawang",
        path: routes.jualAcJatilawang,
        areaName: "Jatilawang",
        localLandmarks: [
          "Jalur selatan Banyumas (Wangon–Rawalo)",
          "Pasar Jatilawang",
          "Kawasan dekat Sungai Serayu",
          "Sentra gula kelapa dan UMKM rumahan",
          "Permukiman dan persawahan sepanjang jalan utama",
        ],
        localBenefits: [
          "AC rumah di Jatilawang banyak yang cari low watt karena daya listrik di permukiman desa sering terbatas",
          "Warung, toko, dan UMKM rumahan butuh unit hemat untuk ruang usaha yang dipakai harian",
          "Pengiriman unit ke alamat lalu pemasangan memudahkan pembeli yang jauh dari pusat kota",
        ],
        localCases: [
          ["Rumah tinggal", "Pemasangan AC kamar yang panas saat siang, dengan pilihan low watt menyesuaikan daya rumah."],
          ["Warung, toko & UMKM", "AC ruang usaha atau ruang produksi rumahan supaya pekerja dan pembeli tidak gerah."],
          ["Kantor desa & ruang layanan", "Pemilihan unit untuk ruang kerja kecil dengan pengiriman ke alamat Jatilawang."],
        ],
        label: "Jual AC Jatilawang",
        title: "Jual AC Jatilawang | Low Watt 900W, Rumah & UMKM — Radja AC",
        description:
          "Beli AC low watt untuk rumah, UMKM, atau toko di Jatilawang? Radja AC cek PK, stok, pengiriman ke desa, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Jatilawang — low watt untuk rumah, UMKM, dan toko desa",
        eyebrow: "Area Banyumas",
        intro:
          "Butuh AC di Jatilawang untuk rumah, toko, ruko, kantor, ruang usaha, atau beberapa unit? Tim Radja AC bantu cek kebutuhan PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan dari data awal.",
        localContext:
          "Jatilawang ada di jalur selatan Banyumas dekat Wangon dan Rawalo, daerah pertanian dan UMKM rumahan—termasuk sentra gula kelapa—dengan permukiman dan toko di sepanjang jalan utama. Pembeli AC di sini umumnya rumah tinggal yang kamarnya panas saat siang, ditambah warung, toko, dan kantor desa. Karena daya listrik rumahan banyak yang terbatas, jual AC Jatilawang sering mengarah ke pilihan low watt. Unit biasanya dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Jatilawang dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
        keywordVariants: [
          "jual AC Jatilawang",
          "AC low watt Jatilawang",
          "AC 900 watt Jatilawang",
          "AC rumah Jatilawang",
          "AC UMKM Jatilawang",
          "AC toko Jatilawang",
          "pasang AC Jatilawang",
          "pengiriman AC Jatilawang",
          "ganti AC lama Jatilawang",
        ],
        nearbyAreaLinks: [
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Wangon", routes.jualAcWangon],
          ["Jual AC Ajibarang", routes.jualAcAjibarang],
          ["Jual AC Rawalo", routes.jualAcRawalo],
        ],
        trustBullets: [
          "Cek kebutuhan PK dari ukuran ruangan, daya listrik, dan pola pemakaian",
          "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
          "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Jatilawang dan jumlah unit",
          "Cocok untuk rumah, toko, ruko, kantor kecil, usaha, dan pembelian beberapa unit",
        ],
        localFaq: [
          [
            "AC rumah di Jatilawang sebaiknya low watt karena listrik terbatas?",
            "Banyak rumah di permukiman Jatilawang pakai daya 900–1300 watt, jadi low watt sering jadi pilihan agar listrik tidak turun. Sebutkan daya listrik dan ukuran kamar untuk cek unit dan stok.",
          ],
          [
            "Bisa kirim AC ke alamat yang agak masuk desa di Jatilawang?",
            "Bisa. Unit dikirim ke alamat lalu pemasangan dijadwalkan sesuai akses lokasi; sebutkan alamat dan jumlah unit untuk perkiraan pengiriman.",
          ],
          [
            "Untuk warung atau UMKM rumahan di Jatilawang, AC-nya bagaimana?",
            "Ruang usaha atau ruang produksi yang dipakai harian sebaiknya pakai kapasitas yang sesuai luas, bukan yang termurah, supaya awet. Sebutkan ukuran ruang dan jam pakai.",
          ],
          [
            "Pembayaran AC di Jatilawang bisa COD atau transfer?",
            "Bisa. Banyak pembeli ambil DP dulu lalu pelunasan COD saat unit datang, atau transfer setelah stok dipastikan.",
          ],
          [
            "AC lama di rumah atau UMKM Jatilawang sudah boros listrik, ganti atau servis?",
            "Kalau unit sudah tua dan tagihan listrik naik terus, ganti ke AC low watt baru jauh lebih hemat. Kirim daya listrik rumah dan ukuran ruangan — tim Radja AC bantu pilih unit yang pas dan tidak bikin MCB turun.",
          ],
        ],
        commonNeeds: [
          "AC rumah tinggal dan kamar tidur",
          "AC toko, ruko, kantor kecil, dan ruang usaha",
          "AC untuk beberapa ruangan atau beberapa titik",
          "Pembelian unit untuk usaha lokal dan kebutuhan banyak unit",
        ],
        buyingChecks: [
          "Alamat detail area Jatilawang",
          "Ukuran ruangan dan estimasi kebutuhan PK",
          "Daya listrik serta pilihan standard, low watt, atau inverter",
          "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
        ],
        paymentNote:
          "Pembayaran fleksibel bisa dikonsultasikan: DP, COD, atau transfer setelah kebutuhan unit, pengiriman, dan opsi pemasangan jelas.",
        relatedLinks: [
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
          ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek AC Jatilawang",
        waIntent: "cek stok AC Jatilawang dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Jatilawang",
      },
  {
        slug: "jual-ac-cilongok",
        path: routes.jualAcCilongok,
        areaName: "Cilongok",
        localLandmarks: [
          "Jalur Purwokerto–Cilongok–Ajibarang",
          "Sentra durian dan gula kelapa Cilongok",
          "Pasar Cilongok",
          "Permukiman dan persawahan desa",
          "Curug dan wisata alam sekitar Cilongok",
        ],
        localBenefits: [
          "AC rumah dan AC kos di permukiman desa Cilongok banyak pilih low watt karena daya listrik terbatas",
          "Toko kecil dan usaha rumahan butuh unit hemat untuk dipakai harian",
          "Pengiriman unit ke alamat desa lalu pemasangan memudahkan pembeli yang jauh dari kota",
        ],
        localCases: [
          ["Rumah & kos desa", "Pemasangan AC kamar yang panas saat siang dengan pilihan low watt sesuai daya."],
          ["Toko kecil & usaha rumahan", "AC ruang usaha atau warung di sepanjang jalan desa."],
          ["Tambah unit bertahap", "Keluarga menambah AC per kamar mengikuti anggaran."],
        ],
        label: "Jual AC Cilongok",
        title: "Jual AC Cilongok untuk Rumah, Toko & Usaha — Radja AC",
        description:
          "Butuh AC untuk rumah, toko, ruko, kantor, atau usaha di Cilongok? Radja AC bantu cek PK, stok, pengiriman, opsi pemasangan, dan pembayaran fleksibel.",
        h1: "Jual AC Cilongok untuk Rumah, Toko & Usaha",
        eyebrow: "Area Banyumas",
        intro:
          "Butuh AC di Cilongok untuk rumah, toko, ruko, kantor, ruang usaha, atau beberapa unit? Tim Radja AC bantu cek kebutuhan PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan dari data awal.",
        localContext:
          "Cilongok ada di sisi barat Banyumas menuju Ajibarang—daerah pertanian dan perdesaan yang dikenal dengan durian dan gula kelapa. Pembeli AC di sini umumnya rumah warga, kos, dan toko kecil di sepanjang jalan desa, dengan daya listrik rumahan yang sering terbatas. Karena itu banyak yang cari AC rumah low watt. Untuk jual AC Cilongok, unit diantar ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Cilongok dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
        keywordVariants: [
          "AC rumah Cilongok",
          "AC toko dan ruko Cilongok",
          "AC kantor kecil Cilongok",
          "AC usaha Cilongok",
          "Banyak unit area Cilongok",
          "Cek PK AC Cilongok",
        ],
        nearbyAreaLinks: [
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Ajibarang", routes.jualAcAjibarang],
          ["Jual AC Karanglewas", routes.jualAcKaranglewas],
          ["Jual AC Jatilawang", routes.jualAcJatilawang],
        ],
        trustBullets: [
          "Cek kebutuhan PK dari ukuran ruangan, daya listrik, dan pola pemakaian",
          "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
          "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Cilongok dan jumlah unit",
          "Cocok untuk rumah, toko, ruko, kantor kecil, usaha, dan pembelian beberapa unit",
        ],
        localFaq: [
          [
            "AC rumah di Cilongok, pas pakai low watt karena listrik terbatas?",
            "Banyak rumah desa di Cilongok pakai daya 900–1300 watt, jadi low watt sering cocok agar listrik tidak turun. Sebutkan daya dan ukuran kamar untuk cek unit dan stok.",
          ],
          [
            "Bisa kirim AC ke alamat yang masuk desa di Cilongok?",
            "Bisa. Unit dikirim ke alamat lalu pemasangan dijadwalkan sesuai akses lokasi; sebutkan alamat dan jumlah unit untuk perkiraan pengiriman.",
          ],
          [
            "Untuk toko kecil atau warung di Cilongok, AC-nya bagaimana?",
            "Ruang usaha yang dipakai harian sebaiknya pakai kapasitas sesuai luas, bukan yang termurah, supaya awet. Sebutkan ukuran ruang dan jam pakai.",
          ],
          [
            "Pembayaran AC di Cilongok bisa COD atau transfer?",
            "Bisa. Banyak pembeli ambil DP dulu lalu pelunasan COD saat unit datang, atau transfer setelah stok dipastikan.",
          ],
        ],
        commonNeeds: [
          "AC rumah tinggal dan kamar tidur",
          "AC toko, ruko, kantor kecil, dan ruang usaha",
          "AC untuk beberapa ruangan atau beberapa titik",
          "Pembelian unit untuk usaha lokal dan kebutuhan banyak unit",
        ],
        buyingChecks: [
          "Alamat detail area Cilongok",
          "Ukuran ruangan dan estimasi kebutuhan PK",
          "Daya listrik serta pilihan standard, low watt, atau inverter",
          "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
        ],
        paymentNote:
          "Pembayaran fleksibel bisa dikonsultasikan: DP, COD, atau transfer setelah kebutuhan unit, pengiriman, dan opsi pemasangan jelas.",
        relatedLinks: [
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
          ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek AC Cilongok",
        waIntent: "cek stok AC Cilongok dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Cilongok",
      },
  {
        slug: "jual-ac-ajibarang",
        path: routes.jualAcAjibarang,
        areaName: "Ajibarang",
        localLandmarks: [
          "Pasar Ajibarang",
          "Terminal Ajibarang",
          "RSUD Ajibarang",
          "Persimpangan jalur Purwokerto–Bumiayu–Tegal",
          "Pertokoan dan ruko pusat kecamatan",
        ],
        localBenefits: [
          "Ruko dan toko di sekitar Pasar Ajibarang cepat pengap saat ramai, jadi butuh AC yang cepat dingin di ruang sempit penuh barang",
          "Apotek, klinik, dan kantor dekat RSUD Ajibarang perlu ruang tunggu yang adem sepanjang jam buka",
          "AC rumah di Ajibarang banyak dipilih untuk kamar dan ruang keluarga dengan pemasangan rapi",
        ],
        localCases: [
          ["Ruko & toko pasar", "Pedagang pasang AC di ruang jualan agar pembeli betah; sebagian beli beberapa unit untuk toko yang luas."],
          ["Apotek, klinik & kantor", "AC ruang tunggu dan ruang layanan dekat RSUD Ajibarang supaya pasien dan staf nyaman."],
          ["Rumah tinggal", "Pemasangan AC kamar dengan pengiriman unit ke alamat di Ajibarang dan sekitarnya."],
        ],
        label: "Jual AC Ajibarang",
        title: "Jual AC Ajibarang | Pasar, RSUD & Jalur Bumiayu — Radja AC",
        description:
          "Beli AC untuk rumah, ruko Pasar Ajibarang, klinik, kantor, atau area Pekuncen–Gumelar–Bumiayu? Radja AC cek PK, stok, dan jadwal pasang via WhatsApp.",
        h1: "Jual AC Ajibarang — rumah, ruko, klinik, dan area jalur Bumiayu",
        eyebrow: "Area Banyumas Barat",
        intro:
          "Butuh AC di Ajibarang untuk rumah, toko, ruko, kantor, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
        localContext:
          "Ajibarang adalah pusat dagang dan persimpangan barat Banyumas menuju Bumiayu dan Tegal, dengan Pasar Ajibarang yang ramai sebagai jantung ekonominya. Pembeli AC di sini banyak dari pemilik ruko dan toko di sekitar pasar, apotek dan klinik dekat RSUD Ajibarang, serta rumah tinggal. Toko yang sempit dan penuh barang cepat pengap saat ramai pembeli, sehingga jual AC Ajibarang sering soal mencari unit yang cepat mendinginkan ruang usaha. Banyak yang beli unit sekaligus pemasangan, dengan pembayaran DP atau transfer setelah stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Ajibarang, pengiriman unit dan opsi pemasangan perlu dikonfirmasi dari alamat detail, jumlah unit, stok, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC toko, ruko, kantor, dan ruang usaha",
          "AC untuk kontrakan, rumah sewa, atau usaha harian",
          "Pembelian beberapa unit untuk usaha lokal, proyek, pengadaan, atau kebutuhan banyak unit",
        ],
        buyingChecks: [
          "Alamat detail area Ajibarang untuk estimasi pengiriman",
          "Ukuran ruangan, tinggi plafon, dan kondisi panas matahari",
          "Daya listrik dan kebutuhan standard, low watt, atau inverter",
          "Jumlah unit, preferensi brand, anggaran, dan kebutuhan pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Katalog AC", routes.katalog],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Split Rumah", routes.katalogAcSplitRumah],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["AC Gree", routes.brandGree],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Ajibarang",
        waIntent: "cek stok AC Ajibarang dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Ajibarang",
        keywordVariants: [
          "jual AC Ajibarang",
          "toko AC Ajibarang",
          "beli AC Ajibarang",
          "AC ruko Pasar Ajibarang",
          "AC klinik Ajibarang",
          "AC RSUD Ajibarang",
          "pasang AC Ajibarang",
          "AC Pekuncen",
          "AC Gumelar",
          "AC Bumiayu dari Ajibarang",
          "pengiriman AC Ajibarang",
          "ganti AC lama Ajibarang",
        ],
        nearbyAreaLinks: [
          ["Purwokerto", routes.jualAcPurwokerto],
          ["Banyumas", routes.jualAcBanyumas],
          ["Baturraden", routes.jualAcBaturraden],
          ["Sokaraja", routes.jualAcSokaraja],
        ],
        trustBullets: [
          "Ajibarang dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Pembeli bisa melihat bukti aktivitas Radja AC melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
          "Untuk area Ajibarang, kebutuhan AC dicek dari alamat detail, ukuran ruangan, daya listrik, jumlah unit, dan opsi pemasangan.",
        ],
        localFaq: [
          [
            "Toko saya dekat Pasar Ajibarang sempit dan penuh barang, AC apa yang cocok?",
            "Ruang sempit yang padat barang dan ramai pembeli cepat pengap, jadi kapasitas dihitung dari luas dan jumlah orang, bukan sekadar yang termurah. Sebutkan ukuran toko untuk cek stok unit yang pas.",
          ],
          [
            "Bisa beli beberapa unit AC sekaligus untuk ruko atau usaha di Ajibarang?",
            "Bisa. Untuk beberapa titik, sebutkan jumlah ruang dan ukurannya; unit dikirim dan pemasangan dijadwalkan, dengan pembayaran DP atau transfer setelah stok dipastikan.",
          ],
          [
            "Melayani pengiriman dan pemasangan AC ke arah Pekuncen, Gumelar, atau Bumiayu dari Ajibarang?",
            "Ya. Unit dikirim ke alamat di jalur Ajibarang–Bumiayu lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat dan jumlah unit untuk perkiraan.",
          ],
          [
            "AC lama di toko atau rumah Ajibarang sudah tidak dingin, ganti atau servis dulu?",
            "Kalau unit sudah sering bermasalah dan biaya servis terus keluar, ganti baru lebih hemat jangka panjang. Kirim kondisi unit lama dan ukuran ruangan — tim Radja AC bantu hitung mana yang lebih masuk akal.",
          ],
        ],
      },
  {
        slug: "jual-ac-wangon",
        path: routes.jualAcWangon,
        areaName: "Wangon",
        localLandmarks: [
          "Pertigaan Wangon (simpul jalur nasional selatan)",
          "Jalur Purwokerto–Cilacap–Bandung",
          "Pasar dan Terminal Wangon",
          "Deretan rumah makan dan SPBU jalur selatan",
          "Ruko dan bengkel di pinggir jalan utama",
        ],
        localBenefits: [
          "Rumah makan dan warung di jalur transit perlu AC yang tetap adem walau pintu sering kebuka dan ruangan penuh saat jam makan siang",
          "Toko dan ruko pinggir jalan nasional cari unit yang kuat dipakai seharian; filter cepat kotor karena debu kendaraan",
          "AC rumah dan AC kos di Wangon banyak yang ambil low watt karena daya listrik rumahan terbatas",
        ],
        localCases: [
          ["Rumah makan & warung transit", "Pemilik pasang AC di ruang makan supaya pelanggan yang singgah betah, dan menambah unit saat ruang makan diperluas."],
          ["Toko kelontong & ruko jalur", "AC dipasang dekat etalase dan kasir agar pemilik dan pembeli tidak kepanasan saat lalu lintas padat."],
          ["Rumah & kos pinggir jalur", "Pemasangan AC kamar dengan pilihan low watt; unit dikirim langsung ke alamat di jalur Wangon."],
        ],
        label: "Jual AC Wangon",
        title: "Jual AC Wangon untuk Rumah, Toko & Usaha — Radja AC",
        description:
          "Butuh AC untuk rumah, toko, ruko, kantor, atau usaha di Wangon? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Wangon untuk Rumah, Toko & Usaha",
        eyebrow: "Area Banyumas Barat & Jalur Selatan",
        intro:
          "Butuh AC di Wangon untuk rumah, toko, warung, ruko, kantor, atau ruang usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
        localContext:
          "Di Wangon, yang paling sering cari AC adalah pemilik rumah makan, warung, dan toko di sekitar pertigaan jalur nasional selatan—jalur ramai Purwokerto–Cilacap–Bandung. Ruang makan dan toko cepat gerah karena pintu nyaris tidak pernah tertutup dan debu kendaraan membuat filter cepat kotor, sehingga banyak yang mencari unit yang kuat dipakai seharian. Untuk jual AC Wangon, pembeli biasanya minta pengiriman langsung ke lokasi pinggir jalur lalu pemasangan, dengan pembayaran DP dulu dan pelunasan transfer atau COD saat unit datang dan stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Wangon, pengiriman unit dan opsi pemasangan dikonfirmasi dari alamat detail, stok, jumlah unit, akses lokasi, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC toko, warung, ruko, dan ruang usaha",
          "AC kontrakan, rumah sewa, dan bangunan pinggir jalan utama",
          "Pembelian beberapa unit untuk usaha lokal, proyek, pengadaan, atau kebutuhan banyak unit",
        ],
        buyingChecks: [
          "Alamat detail area Wangon untuk estimasi pengiriman",
          "Ukuran ruangan, tinggi plafon, dan kondisi panas matahari",
          "Daya listrik dan kebutuhan standard, low watt, atau inverter",
          "Jumlah unit, anggaran, preferensi brand, dan kebutuhan pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Ajibarang", routes.jualAcAjibarang],
          ["Katalog AC", routes.katalog],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["AC Gree", routes.brandGree],
          ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
          ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Wangon",
        waIntent: "cek stok AC Wangon dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Wangon",
        keywordVariants: [
          "jual AC Wangon",
          "toko AC Wangon",
          "beli AC Wangon",
          "pengiriman AC Wangon",
          "pemasangan AC Wangon",
          "AC rumah Wangon",
          "AC toko Wangon",
          "AC ruko Wangon",
        ],
        nearbyAreaLinks: [
          ["Ajibarang", routes.jualAcAjibarang],
          ["Rawalo", routes.jualAcRawalo],
          ["Patikraja", routes.jualAcPatikraja],
          ["Banyumas", routes.jualAcBanyumas],
        ],
        trustBullets: [
          "Wangon dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
          "Untuk area Wangon, kebutuhan AC dicek dari alamat detail, ukuran ruangan, daya listrik, jumlah unit, dan opsi pemasangan.",
        ],
        localFaq: [
          [
            "Banyak yang beli AC untuk rumah makan di jalur Wangon, unitnya kuat dipakai seharian?",
            "Untuk ruang makan ramai yang pintunya sering kebuka, kapasitas diambil sedikit lebih besar dari kamar biasa supaya dingin tetap merata. Sebutkan luas ruang makan dan jumlah meja agar bisa dicek stok unit yang cocok.",
          ],
          [
            "Bisa kirim dan pasang AC ke toko atau ruko di pinggir jalur Wangon?",
            "Bisa. Pengiriman unit diantar ke alamat di jalur Wangon lalu pemasangan dijadwalkan; banyak pembeli ambil DP dulu dan pelunasan transfer atau COD saat unit sampai.",
          ],
          [
            "AC rumah atau AC kos di Wangon sebaiknya pilih apa kalau listrik terbatas?",
            "Rumah dan kos dengan daya 900–1300 watt biasanya pakai low watt agar listrik tidak turun. Sebutkan daya listrik dan jumlah kamar untuk cek pilihan unit dan stok.",
          ],
          [
            "Di pinggir jalan ramai filter AC cepat kotor, ada saran?",
            "Debu kendaraan memang mempercepat filter kotor, jadi unit dengan filter yang gampang dibersihkan lebih praktis untuk toko dan rumah makan jalur. Perawatan rutin menjaga AC tetap dingin dan hemat listrik.",
          ],
        ],
      },
  {
        slug: "jual-ac-karanglewas",
        path: routes.jualAcKaranglewas,
        areaName: "Karanglewas",
        localLandmarks: [
          "Perumahan Griya Satria dan cluster perumahan baru di Karanglewas",
          "Jalan Karanglewas–Purwokerto (jalur barat menuju pusat kota)",
          "Pasar Karanglewas dan deretan ruko di jalan utama",
          "Kawasan kos dan hunian dekat kampus sisi barat Purwokerto",
          "Akses ke Cilongok dan Kedungbanteng via jalur barat",
        ],
        localBenefits: [
          "Perumahan baru di Karanglewas banyak yang pasang AC kamar utama dan ruang keluarga sekaligus saat baru pindah, jadi sering beli 2–3 unit sekaligus",
          "Ruko dan toko di jalan utama Karanglewas butuh ruang yang adem buat pembeli, terutama siang hari saat jalur ramai",
          "Kos dan hunian dekat kampus sisi barat cocok pakai low watt agar daya per kamar tidak turun saat beberapa unit menyala bersamaan",
        ],
        localCases: [
          ["Perumahan baru", "Keluarga baru pindah pasang AC kamar utama dan ruang keluarga sekaligus dengan jalur pipa yang rapi."],
          ["Ruko & toko jalan utama", "AC area pelanggan di ruko Karanglewas agar pembeli betah saat siang yang panas."],
          ["Kos & hunian kampus", "Pemilik kos pasang unit hemat daya per kamar secara bertahap mengikuti anggaran."],
        ],
        label: "Jual AC Karanglewas",
        title: "Jual AC Karanglewas untuk Rumah, Kost & Usaha — Radja AC",
        description:
          "Butuh AC untuk rumah, kost, toko, kantor, ruko, atau usaha di Karanglewas? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Karanglewas untuk Rumah, Kost & Usaha",
        eyebrow: "Area Ring Purwokerto",
        intro:
          "Butuh AC di Karanglewas untuk rumah, kamar, kost, toko, kantor, ruko, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
        localContext:
          "Karanglewas adalah ring barat Purwokerto yang berkembang pesat dengan perumahan baru, ruko, dan kos mahasiswa. Jalur Karanglewas–Purwokerto menghubungkan kawasan ini langsung ke pusat kota, sehingga banyak keluarga muda yang baru pindah ke perumahan seperti Griya Satria memilih pasang AC kamar utama dan ruang keluarga sekaligus. Ruko di jalan utama butuh ruang yang adem buat pembeli saat siang, sedangkan kos dekat kampus sisi barat sering cari low watt agar daya per kamar aman. Karena dekat basis layanan Banyumas, pengiriman unit dan survei lokasi mudah dijadwalkan. Pembayaran bisa DP, COD, atau transfer setelah stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Karanglewas, pengiriman unit dan opsi pemasangan dikonfirmasi dari alamat detail, stok, jumlah unit, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC kost, kontrakan, dan rumah sewa",
          "AC toko, kantor, ruko, dan ruang usaha",
          "Pembelian beberapa unit untuk rumah banyak ruangan atau usaha lokal",
        ],
        buyingChecks: [
          "Alamat detail area Karanglewas untuk estimasi pengiriman",
          "Ukuran ruangan, tinggi plafon, dan paparan panas matahari",
          "Daya listrik dan kebutuhan standard, low watt, atau inverter",
          "Jumlah unit, anggaran, preferensi brand, dan kebutuhan pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Baturraden", routes.jualAcBaturraden],
          ["Katalog AC", routes.katalog],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Split Rumah", routes.katalogAcSplitRumah],
          ["AC Inverter", routes.katalogAcInverter],
          ["AC Daikin", routes.brandDaikin],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Karanglewas",
        waIntent: "cek stok AC Karanglewas dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Karanglewas",
        keywordVariants: [
          "jual AC Karanglewas",
          "toko AC Karanglewas",
          "beli AC Karanglewas",
          "pengiriman AC Karanglewas",
          "pemasangan AC Karanglewas",
          "AC rumah Karanglewas",
          "AC kost Karanglewas",
        ],
        nearbyAreaLinks: [
          ["Purwokerto", routes.jualAcPurwokerto],
          ["Baturraden", routes.jualAcBaturraden],
          ["Kembaran", routes.jualAcKembaran],
          ["Sokaraja", routes.jualAcSokaraja],
        ],
        trustBullets: [
          "Karanglewas dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Pembeli bisa melihat bukti aktivitas Radja AC melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
          "Untuk area Karanglewas, kebutuhan AC dicek dari ukuran ruangan, daya listrik, alamat detail, jumlah unit, dan opsi pemasangan.",
        ],
        localFaq: [
          [
            "Baru pindah ke perumahan di Karanglewas, pasang AC kamar utama dan ruang keluarga sekaligus bisa?",
            "Bisa. Banyak keluarga baru di perumahan Karanglewas pasang 2–3 unit sekaligus. Kirim jumlah ruangan, ukuran, dan daya listrik — tim Radja AC bantu cek stok dan jadwal pemasangan sekaligus.",
          ],
          [
            "AC untuk ruko di jalan utama Karanglewas, kuat dipakai seharian?",
            "Ruko yang ramai pembeli dan pintunya sering terbuka butuh kapasitas sesuai luas. Sebutkan ukuran ruang usaha dan jam buka untuk cek unit yang pas.",
          ],
          [
            "AC kos dekat kampus sisi barat Purwokerto di Karanglewas, hemat listrik?",
            "Kos dengan banyak kamar dan daya terbatas banyak pakai low watt agar listrik tidak turun saat beberapa unit menyala. Sebutkan daya total dan jumlah kamar untuk arahan.",
          ],
          [
            "Bisa kirim dan pasang AC ke alamat di Karanglewas?",
            "Bisa. Karanglewas dekat pusat kota dan basis layanan Banyumas, jadi pengiriman unit dan survei lokasi mudah dijadwalkan. Sebutkan alamat dan jumlah unit.",
          ],
        ],
      },
  {
        slug: "jual-ac-kembaran",
        path: routes.jualAcKembaran,
        areaName: "Kembaran",
        localLandmarks: [
          "Kampus UNSOED Karangwangkal (sisi timur Purwokerto)",
          "Jalur Purwokerto–Sokaraja via Kembaran",
          "Kawasan kos padat di sekitar Karangwangkal dan Dukuhwaluh",
          "Pasar Kembaran dan deretan warung serta toko lokal",
          "Perumahan warga di ring timur Purwokerto",
        ],
        localBenefits: [
          "Kos dan kontrakan di sekitar Karangwangkal dan Dukuhwaluh butuh unit hemat daya per kamar agar daya total bangunan tidak turun saat banyak AC menyala bersamaan",
          "Pemilik kos sering beli tipe seragam supaya kalau ada unit rusak, penggantian dan perawatan lebih mudah dan tidak perlu stok sparepart berbeda",
          "Rumah warga di ring timur Purwokerto yang terasa panas saat siang banyak pilih inverter untuk kamar utama karena AC menyala hampir setiap malam",
        ],
        localCases: [
          ["Kos padat dekat UNSOED", "Pemilik kos di Karangwangkal pasang unit hemat daya tipe seragam per kamar secara bertahap."],
          ["Kontrakan & rumah sewa", "AC kamar untuk hunian sewa dengan daya listrik standar; tipe seragam memudahkan perawatan."],
          ["Rumah tinggal warga", "Keluarga pasang AC kamar utama dengan inverter untuk pemakaian malam yang panjang."],
        ],
        localFaq: [
          [
            "AC untuk kos banyak kamar di sekitar Karangwangkal Kembaran, pakai apa?",
            "Untuk banyak kamar kecil, unit hemat daya tipe seragam biasanya cocok agar daya total bangunan tidak turun. Kirim jumlah kamar dan daya listrik total untuk arahan unit dan stok.",
          ],
          [
            "Bisa pasang AC bertahap untuk kontrakan atau rumah sewa di Kembaran?",
            "Bisa. Banyak pemilik di Dukuhwaluh dan Karangwangkal pasang per kamar secara bertahap. Kirim jumlah kamar dan target jadwal agar tim menyiapkan tipe seragam dan estimasi biaya.",
          ],
          [
            "AC low watt cukup untuk kos di Kembaran dengan daya terbatas?",
            "Sering cocok, tergantung jumlah unit yang menyala bersamaan dan daya total bangunan. Kirim daya listrik dan jumlah kamar agar dicek kecocokannya sebelum deal.",
          ],
          [
            "Rumah di ring timur Purwokerto area Kembaran, inverter atau standard?",
            "Untuk kamar utama yang AC-nya menyala hampir setiap malam, inverter lebih hemat jangka panjang. Untuk kamar tambahan yang jarang dipakai, standard sudah cukup. Sebutkan pola pemakaian untuk arahan.",
          ],
        ],
        label: "Jual AC Kembaran",
        title: "Jual AC Kembaran untuk Rumah, Kost & Usaha — Radja AC",
        description:
          "Butuh AC untuk rumah, kost, kontrakan, toko, atau usaha di Kembaran? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Kembaran untuk Rumah, Kost & Usaha",
        eyebrow: "Area Kampus & Hunian Banyumas",
        intro:
          "Butuh AC di Kembaran untuk rumah, kost, kontrakan, toko, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
        localContext:
          "Kembaran adalah ring hunian di timur Purwokerto, berbatasan langsung dengan kampus UNSOED Karangwangkal dan kawasan kos padat di Dukuhwaluh. Permintaan AC paling banyak dari pemilik kos yang ingin unit hemat daya tipe seragam agar daya total bangunan tidak turun saat banyak kamar menyala bersamaan, serta rumah tinggal warga yang kamar utamanya panas saat siang. Jalur Kembaran–Sokaraja juga memudahkan pengiriman unit dari gudang Radja AC di Pamijen. Pemilik kos sering pasang per kamar secara bertahap, sehingga efisiensi daya dan keseragaman tipe jadi pertimbangan utama.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Kembaran, pengiriman unit dan opsi pemasangan dikonfirmasi dari alamat detail, stok, jumlah unit, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC kost, kontrakan, dan rumah sewa",
          "AC toko, kantor, ruko, dan ruang usaha",
          "Pembelian beberapa unit untuk kamar sewa atau bangunan banyak ruangan",
        ],
        buyingChecks: [
          "Alamat detail area Kembaran untuk estimasi pengiriman",
          "Ukuran ruangan, jumlah kamar, dan jam pemakaian",
          "Daya listrik dan kebutuhan standard, low watt, atau inverter",
          "Jumlah unit, anggaran, preferensi brand, dan kebutuhan pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Sokaraja", routes.jualAcSokaraja],
          ["Katalog AC", routes.katalog],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["Pengadaan AC Kost & Apartemen", routes.pengadaanKostApartemen],
          ["AC Gree", routes.brandGree],
          ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Kembaran",
        waIntent: "cek stok AC Kembaran dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Kembaran",
        keywordVariants: [
          "jual AC Kembaran",
          "toko AC Kembaran",
          "beli AC Kembaran",
          "pengiriman AC Kembaran",
          "pemasangan AC Kembaran",
          "AC kost Kembaran",
          "AC kontrakan Kembaran",
        ],
        nearbyAreaLinks: [
          ["Purwokerto", routes.jualAcPurwokerto],
          ["Sokaraja", routes.jualAcSokaraja],
          ["Karanglewas", routes.jualAcKaranglewas],
          ["Banyumas", routes.jualAcBanyumas],
        ],
        trustBullets: [
          "Kembaran dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Untuk kost, kontrakan, atau bangunan banyak kamar, jumlah ruangan dan daya listrik perlu dicek sejak awal.",
          "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
        ],
      },
  {
        slug: "jual-ac-patikraja",
        path: routes.jualAcPatikraja,
        areaName: "Patikraja",
        localLandmarks: [
          "Jembatan Serayu Patikraja dan aliran Sungai Serayu",
          "Jalur Purwokerto–Patikraja–Banyumas (jalan selatan)",
          "Pasar Patikraja dan deretan toko serta warung di jalan utama",
          "Kawasan persawahan dan permukiman desa Patikraja",
          "Sentra UMKM dan usaha rumahan di sepanjang jalur selatan",
        ],
        localBenefits: [
          "Rumah di Patikraja yang menghadap barat atau dekat persawahan terasa panas saat siang, sehingga AC kamar jadi kebutuhan utama bukan sekadar kenyamanan tambahan",
          "UMKM dan toko di jalur selatan Patikraja butuh ruang yang adem agar pembeli betah, terutama saat jam ramai siang hari",
          "Daya listrik rumahan di permukiman desa Patikraja banyak yang terbatas, sehingga low watt jadi pilihan agar MCB tidak turun saat AC menyala",
        ],
        localCases: [
          ["Rumah tinggal", "AC kamar yang panas saat siang, terutama kamar yang menghadap barat atau dekat atap seng."],
          ["UMKM & toko jalur selatan", "AC ruang usaha agar pembeli betah dan pemilik tidak kelelahan saat jam ramai."],
          ["Kost & rumah sewa", "Unit hemat daya untuk beberapa kamar dengan daya listrik terbatas."],
        ],
        label: "Jual AC Patikraja",
        title: "Jual AC Patikraja untuk Rumah, Toko & Usaha — Radja AC",
        description:
          "Butuh AC untuk rumah, toko, kantor, ruko, atau usaha di Patikraja? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Patikraja untuk Rumah, Toko & Usaha",
        eyebrow: "Area Selatan Purwokerto",
        intro:
          "Butuh AC di Patikraja untuk rumah, toko, kantor, ruko, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
        localContext:
          "Patikraja ada di jalur selatan Purwokerto menuju Banyumas, dibelah Sungai Serayu dengan Jembatan Serayu Patikraja sebagai penanda utamanya. Daerah ini campuran permukiman desa, persawahan, dan UMKM serta toko di sepanjang jalan utama. Rumah yang menghadap barat atau dekat atap seng terasa panas saat siang, sehingga AC kamar jadi kebutuhan nyata. Toko dan UMKM di jalur selatan butuh ruang yang adem agar pembeli betah. Karena daya listrik rumahan banyak yang terbatas, low watt sering jadi pilihan. Unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Patikraja, pengiriman unit dan opsi pemasangan dikonfirmasi dari alamat detail, stok, jumlah unit, akses lokasi, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC toko, kantor, ruko, dan ruang usaha",
          "AC kontrakan, rumah sewa, atau bangunan keluarga",
          "Pembelian beberapa unit untuk usaha lokal, proyek, pengadaan, atau kebutuhan banyak unit",
        ],
        buyingChecks: [
          "Alamat detail area Patikraja untuk estimasi pengiriman",
          "Ukuran ruangan, tinggi plafon, dan kondisi panas matahari",
          "Daya listrik dan kebutuhan standard, low watt, atau inverter",
          "Jumlah unit, anggaran, preferensi brand, dan kebutuhan pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Katalog AC", routes.katalog],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Split Rumah", routes.katalogAcSplitRumah],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["AC Sharp", routes.brandSharp],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Patikraja",
        waIntent: "cek stok AC Patikraja dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Patikraja",
        keywordVariants: [
          "jual AC Patikraja",
          "toko AC Patikraja",
          "beli AC Patikraja",
          "pengiriman AC Patikraja",
          "pemasangan AC Patikraja",
          "AC rumah Patikraja",
          "AC toko Patikraja",
        ],
        nearbyAreaLinks: [
          ["Banyumas", routes.jualAcBanyumas],
          ["Rawalo", routes.jualAcRawalo],
          ["Purwokerto", routes.jualAcPurwokerto],
          ["Wangon", routes.jualAcWangon],
        ],
        trustBullets: [
          "Patikraja dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Untuk area Patikraja, kebutuhan AC dicek dari alamat detail, ukuran ruangan, daya listrik, jumlah unit, dan opsi pemasangan.",
          "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
        ],
        localFaq: [
          [
            "Rumah di Patikraja kamarnya panas saat siang, AC apa yang cocok?",
            "Kamar yang menghadap barat atau dekat atap seng memang lebih cepat panas. Kapasitas PK dihitung dari luas kamar dan kondisi panas tersebut, bukan sekadar ukuran standar. Sebutkan ukuran kamar dan arah hadap untuk arahan yang lebih tepat.",
          ],
          [
            "AC untuk UMKM atau toko di jalur selatan Patikraja, pilih apa?",
            "Ruang usaha yang dipakai seharian dan ramai pembeli butuh kapasitas sesuai luas, bukan yang termurah, supaya dingin merata dan awet. Sebutkan ukuran ruang dan jam buka untuk cek unit.",
          ],
          [
            "Daya listrik rumah di Patikraja terbatas, AC low watt cukup?",
            "Banyak rumah di permukiman desa Patikraja pakai daya 900–1300 watt, jadi low watt sering jadi pilihan agar MCB tidak turun. Sebutkan daya dan ukuran kamar untuk cek unit dan stok.",
          ],
          [
            "Bisa kirim dan pasang AC ke alamat di jalur Patikraja dekat Jembatan Serayu?",
            "Bisa. Unit dikirim ke alamat di jalur selatan Patikraja lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat dan jumlah unit untuk perkiraan pengiriman.",
          ],
        ],
      },
  {
        slug: "jual-ac-rawalo",
        path: routes.jualAcRawalo,
        areaName: "Rawalo",
        localLandmarks: [
          "Pertigaan Rawalo (simpul jalur Purwokerto–Buntu–Wangon)",
          "Jembatan Serayu Rawalo dan aliran Sungai Serayu",
          "Pasar Rawalo dan deretan toko serta warung di jalan utama",
          "Kawasan persawahan dan permukiman desa Rawalo",
          "Jalur menuju Buntu dan Majenang (selatan Banyumas)",
        ],
        localBenefits: [
          "Toko dan warung di pertigaan Rawalo yang ramai kendaraan butuh AC ruang pelanggan agar pembeli betah singgah, terutama siang hari saat jalur panas",
          "Rumah di permukiman desa Rawalo yang terasa panas saat siang banyak pilih low watt karena daya listrik rumahan terbatas",
          "Posisi Rawalo di pertigaan jalur utama memudahkan penjadwalan pengiriman unit dari gudang Sokaraja ke alamat tujuan",
        ],
        localCases: [
          ["Toko & warung pertigaan", "AC ruang pelanggan di pertigaan Rawalo agar pembeli yang singgah betah dan tidak buru-buru pergi."],
          ["Rumah tinggal desa", "Pendinginan kamar yang panas saat siang dengan pilihan low watt sesuai daya rumahan."],
          ["Kantor kecil & usaha", "Pemilihan kapasitas AC sesuai luas ruang kerja dengan pengiriman ke alamat Rawalo."],
        ],
        label: "Jual AC Rawalo",
        title: "Jual AC Rawalo untuk Rumah, Toko & Usaha — Radja AC",
        description:
          "Butuh AC untuk rumah, toko, kantor, ruko, atau usaha di Rawalo? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Rawalo untuk Rumah, Toko & Usaha",
        eyebrow: "Area Selatan Banyumas",
        intro:
          "Butuh AC di Rawalo untuk rumah, toko, kantor, ruko, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
        localContext:
          "Rawalo adalah pertigaan jalur selatan Banyumas yang menghubungkan Purwokerto ke Buntu dan Wangon, dengan Jembatan Serayu Rawalo sebagai penanda geografisnya. Daerah ini campuran permukiman desa, persawahan, dan usaha tepi jalan di sekitar pertigaan. Toko dan warung di pertigaan yang ramai kendaraan butuh AC ruang pelanggan agar pembeli betah singgah, sedangkan rumah di permukiman desa banyak yang pilih low watt karena daya listrik terbatas. Posisi Rawalo di jalur utama memudahkan penjadwalan pengiriman unit dari gudang Sokaraja. Pembayaran bisa DP, COD, atau transfer setelah stok dipastikan.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Rawalo, pengiriman unit dan opsi pemasangan dikonfirmasi dari alamat detail, stok, jumlah unit, akses lokasi, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC toko, kantor, ruko, dan ruang usaha",
          "AC kontrakan, rumah sewa, atau bangunan keluarga",
          "Pembelian beberapa unit untuk usaha lokal, proyek, pengadaan, atau kebutuhan banyak unit",
        ],
        buyingChecks: [
          "Alamat detail area Rawalo untuk estimasi pengiriman",
          "Ukuran ruangan, tinggi plafon, dan kondisi panas matahari",
          "Daya listrik dan kebutuhan standard, low watt, atau inverter",
          "Jumlah unit, anggaran, preferensi brand, dan kebutuhan pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Wangon", routes.jualAcWangon],
          ["Katalog AC", routes.katalog],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["AC Low Watt", routes.katalogAcLowWatt],
          ["AC Gree", routes.brandGree],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Rawalo",
        waIntent: "cek stok AC Rawalo dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Rawalo",
        keywordVariants: [
          "jual AC Rawalo",
          "toko AC Rawalo",
          "beli AC Rawalo",
          "pengiriman AC Rawalo",
          "pemasangan AC Rawalo",
          "AC rumah Rawalo",
          "AC toko Rawalo",
        ],
        nearbyAreaLinks: [
          ["Banyumas", routes.jualAcBanyumas],
          ["Patikraja", routes.jualAcPatikraja],
          ["Wangon", routes.jualAcWangon],
          ["Ajibarang", routes.jualAcAjibarang],
        ],
        trustBullets: [
          "Rawalo dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Untuk area Rawalo, kebutuhan AC dicek dari alamat detail, ukuran ruangan, daya listrik, jumlah unit, dan opsi pemasangan.",
          "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
        ],
        localFaq: [
          [
            "AC untuk toko atau warung di pertigaan Rawalo yang ramai kendaraan, pilih apa?",
            "Ruang usaha di pertigaan yang pintunya sering terbuka dan ramai pembeli butuh kapasitas sedikit lebih besar dari kamar biasa agar dingin merata. Sebutkan ukuran ruang dan jam buka untuk cek unit dan stok.",
          ],
          [
            "Rumah di permukiman desa Rawalo, daya listrik terbatas, AC apa yang aman?",
            "Banyak rumah di Rawalo pakai daya 900–1300 watt, jadi low watt sering jadi pilihan agar MCB tidak turun saat AC menyala. Sebutkan daya dan ukuran kamar untuk cek unit.",
          ],
          [
            "Bisa kirim dan pasang AC ke alamat di jalur Rawalo dekat Jembatan Serayu?",
            "Bisa. Posisi Rawalo di pertigaan jalur utama memudahkan penjadwalan pengiriman dari gudang Sokaraja. Sebutkan alamat dan jumlah unit untuk perkiraan.",
          ],
          [
            "Melayani pengiriman ke arah Buntu atau Majenang dari Rawalo?",
            "Untuk area di jalur selatan Rawalo menuju Buntu dan Majenang, unit dikirim ke alamat lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat detail dan jumlah unit.",
          ],
        ],
      },
  {
        slug: "jual-ac-baturraden",
        path: routes.jualAcBaturraden,
        areaName: "Baturraden",
        localLandmarks: [
          "Lokawisata Baturraden dan kolam renang air panas",
          "Jalur wisata Purwokerto–Baturraden (Jl. Raya Baturraden)",
          "Kawasan villa dan homestay di lereng Gunung Slamet",
          "Kafe dan warung makan di sepanjang jalur wisata",
          "Permukiman warga di Karangmangu dan Kemutug Lor",
        ],
        localBenefits: [
          "Homestay dan villa di lereng Slamet butuh AC kamar tamu yang seragam dan mudah dirawat saat musim liburan ramai",
          "Kafe dan warung di jalur wisata perlu ruang yang tetap adem walau pintu sering terbuka dan pengunjung padat saat akhir pekan",
          "Rumah warga di area bawah yang terasa panas saat siang cukup pasang AC di kamar tertentu, bukan seluruh bangunan",
        ],
        localCases: [
          ["Homestay & villa wisata", "Pemilihan AC kamar tamu seragam untuk penginapan yang ramai saat akhir pekan dan libur panjang."],
          ["Kafe & warung jalur wisata", "AC ruang pelanggan agar pengunjung betah walau lalu lintas wisata padat."],
          ["Rumah kawasan lereng", "Sebagian rumah hanya butuh AC di kamar yang panas saat siang, bukan seluruh ruangan."],
        ],
        label: "Jual AC Baturraden",
        title: "Jual AC Baturraden untuk Rumah, Villa & Penginapan — Radja AC",
        description:
          "Butuh AC untuk rumah, villa, homestay, guest house, atau usaha di Baturraden? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
        h1: "Jual AC Baturraden untuk Rumah, Villa & Penginapan",
        eyebrow: "Area Wisata Banyumas",
        intro:
          "Butuh AC di Baturraden atau Baturaden untuk rumah, villa, homestay, guest house, atau ruang usaha? Tim Radja AC cek kebutuhan PK, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan dari data lokasi.",
        localContext:
          "Baturraden adalah kawasan wisata alam di kaki Gunung Slamet, sekitar 14 km utara Purwokerto, yang dikenal dengan Lokawisata Baturraden, kolam renang air panas, dan udara sejuk. Jalur wisata Purwokerto–Baturraden dipenuhi homestay, villa, kafe, dan warung makan yang ramai saat akhir pekan dan musim liburan. Kebutuhan AC di sini berbeda: penginapan butuh kamar tamu yang adem dan seragam saat okupansi naik, kafe butuh ruang pelanggan yang nyaman walau pintu sering terbuka, sedangkan rumah warga di area bawah yang panas saat siang cukup pasang AC di kamar tertentu. Tim Radja AC mengecek jumlah kamar, ukuran ruangan, daya listrik, dan pola pemakaian sebelum unit dikirim dari gudang Sokaraja.",
        coverageNote:
          "Showroom dan gudang Radja AC berada di Pamijen, Sokaraja, Banyumas. Untuk area Baturraden atau Baturaden, pengiriman unit dan opsi pemasangan dikonfirmasi berdasarkan alamat, jumlah unit, akses lokasi, stok, dan jadwal.",
        commonNeeds: [
          "AC rumah tinggal, kamar tidur, dan ruang keluarga",
          "AC villa, homestay, guest house, dan kamar sewa",
          "AC cafe, toko, ruang usaha, dan area tamu",
          "Kebutuhan beberapa unit untuk penginapan atau usaha hospitality",
        ],
        buyingChecks: [
          "Alamat detail Baturraden atau Baturaden untuk estimasi pengiriman",
          "Jumlah kamar atau ruangan yang akan memakai AC",
          "Ukuran ruangan, daya listrik, dan jam pemakaian",
          "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
        ],
        relatedLinks: [
          ["Jual AC Purwokerto", routes.jualAcPurwokerto],
          ["Jual AC Banyumas", routes.jualAcBanyumas],
          ["Jual AC Sokaraja", routes.jualAcSokaraja],
          ["Kalkulator PK AC", routes.kalkulatorPkAc],
          ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
          ["AC Inverter", routes.katalogAcInverter],
          ["Pengadaan AC Hotel & Guest House", routes.pengadaanHotelGuestHouse],
          ["AC Daikin", routes.brandDaikin],
          ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
          ["Kontak Radja AC", routes.kontak],
        ],
        ctaLabel: "Chat WhatsApp untuk cek stok AC Baturraden",
        waIntent: "cek stok AC Baturraden atau Baturaden dengan data ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
        waArea: "Baturraden",
        keywordVariants: [
          "jual AC Baturraden",
          "jual AC Baturaden",
          "toko AC Baturraden",
          "beli AC Baturraden",
          "pengiriman AC Baturraden",
          "pemasangan AC Baturraden",
          "AC villa Baturraden",
          "AC homestay Baturraden",
          "AC guest house Baturraden",
        ],
        nearbyAreaLinks: [
          ["Purwokerto", routes.jualAcPurwokerto],
          ["Banyumas", routes.jualAcBanyumas],
          ["Sokaraja", routes.jualAcSokaraja],
          ["Ajibarang", routes.jualAcAjibarang],
        ],
        trustBullets: [
          "Baturraden atau Baturaden dilayani dari showroom dan gudang Radja AC di Pamijen, Sokaraja, Banyumas.",
          "Untuk villa, homestay, guest house, atau penginapan, jumlah kamar dan pola pemakaian perlu dibaca sebelum memilih unit.",
          "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi pengiriman, stok fisik, dan pemasangan.",
        ],
        localFaq: [
          [
            "AC untuk kamar homestay atau villa di lereng Baturraden, pilih apa?",
            "Kamar tamu yang dipakai saat liburan panjang sebaiknya unit seragam yang mudah dirawat; inverter lebih efisien kalau AC menyala hampir setiap malam. Kirim jumlah kamar dan ukurannya untuk arahan stok.",
          ],
          [
            "Baturraden kan sejuk, semua ruangan perlu AC?",
            "Tidak selalu. Banyak rumah warga di Karangmangu dan Kemutug Lor hanya pasang AC di kamar yang panas saat siang, bukan seluruh bangunan. Penginapan biasanya pasang di kamar tamu saja. Sebutkan ruangannya untuk masukan.",
          ],
          [
            "Bisa kirim dan pasang AC ke kafe atau warung di jalur wisata Baturraden?",
            "Bisa. Unit dikirim ke alamat di Jl. Raya Baturraden lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat dan jumlah unit; pembayaran bisa DP atau transfer setelah stok dipastikan.",
          ],
          [
            "Pengadaan AC banyak kamar untuk homestay atau villa di Baturraden, bisa?",
            "Bisa. Untuk beberapa kamar sekaligus, kirim jumlah kamar, ukuran, daya listrik, dan target musim ramai agar tim menyiapkan unit seragam, stok, dan jadwal pengiriman bertahap.",
          ],
        ],
      },
  {
      slug: "jual-ac-sumbang",
      path: routes.jualAcSumbang,
      areaName: "Sumbang",
      localContext:
        "Sumbang ada di ring utara-timur Purwokerto, di jalur menuju kaki Gunung Slamet dan Baturraden, jadi sebagian wilayahnya mulai sejuk sementara area bawahnya tetap panas saat siang. Pembeli AC umumnya rumah warga, kos dan kontrakan (sebagian dekat kampus), serta toko dan usaha kecil. Karena masih dekat basis layanan Banyumas, pengiriman unit dan survei lokasi mudah dijadwalkan. Untuk jual AC Sumbang, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      localLandmarks: [
        "Jalur Purwokerto–Sumbang menuju Baturraden",
        "Kawasan kos dekat kampus (sisi utara Purwokerto)",
        "Pasar dan permukiman Sumbang",
        "Area perbukitan kaki Gunung Slamet",
        "Persawahan dan usaha lokal",
      ],
      localBenefits: [
        "Masih dekat basis layanan Banyumas, jadi pengiriman unit dan survei lokasi mudah dijadwalkan",
        "AC rumah dan AC kos banyak pilih low watt menyesuaikan daya listrik rumahan",
        "Area bawah yang panas saat siang butuh pendinginan kamar, sedangkan sisi atas yang sejuk lebih selektif",
      ],
      localCases: [
        ["Rumah & kos warga", "Pemasangan AC kamar yang panas saat siang dengan pilihan low watt."],
        ["Toko & usaha kecil", "AC ruang usaha di sepanjang jalur Sumbang agar pelanggan nyaman."],
        ["Tambah unit bertahap", "Keluarga atau pemilik kos menambah AC per kamar mengikuti anggaran."],
      ],
      label: "Jual AC Sumbang",
      title: "Jual AC Sumbang untuk Rumah, Kost & Usaha — Radja AC",
      description:
        "Butuh AC untuk rumah, kost, toko, kantor kecil, atau usaha di Sumbang? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
      h1: "Jual AC Sumbang untuk Rumah, Kost & Usaha",
      eyebrow: "Area Banyumas Utara / Timur",
      intro:
        "Butuh AC di Sumbang untuk rumah, kost, kontrakan, toko, kantor kecil, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
      parentAreaName: "Banyumas",
      parentAreaPath: routes.jualAcBanyumas,
      priority: "P1",
      localAngle:
        "Sumbang dekat dengan ring Purwokerto bagian utara/timur dan cocok diposisikan sebagai child Banyumas yang mendukung kebutuhan rumah, toko, dan usaha lokal.",
      nearbyAreaLinks: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Kembaran", routes.jualAcKembaran],
        ["Jual AC Baturraden", routes.jualAcBaturraden],
      ],
      keywordVariantsOverride: [
        "jual AC Sumbang",
        "AC rumah Sumbang",
        "AC kost Sumbang",
        "AC toko Sumbang",
        "AC kantor kecil Sumbang",
        "cek stok AC Sumbang",
        "pengiriman AC Sumbang",
        "opsi pemasangan AC Sumbang",
        "AC banyak unit Sumbang",
      ],
      commonNeedsOverride: [
        "AC kamar tidur dan ruang keluarga untuk rumah area Sumbang",
        "AC kost, kontrakan, dan rumah sewa sekitar Sumbang",
        "AC toko, warung, ruko kecil, kantor kecil, dan ruang usaha lokal",
        "Pembelian beberapa unit untuk rumah keluarga, usaha, properti sewa, atau kebutuhan bertahap",
      ],
      buyingChecksOverride: [
        "Alamat detail area Sumbang dan akses pengiriman dari Banyumas",
        "Ukuran ruangan, tinggi plafon, dan paparan panas siang hari",
        "Daya listrik rumah/usaha serta kebutuhan standard, low watt, atau inverter",
        "Jumlah unit, preferensi brand, anggaran, dan kebutuhan unit saja atau opsi pemasangan",
      ],
      trustBulletsOverride: [
        "Sumbang diposisikan sebagai ring utara/timur Purwokerto yang masih dekat dengan basis layanan Banyumas.",
        "Kebutuhan AC dibaca dari ukuran ruangan, daya listrik, jumlah unit, stok aktif, dan alamat detail.",
        "Pengiriman dan opsi pemasangan dikonfirmasi dari data lokasi, akses pekerjaan, dan jadwal yang memungkinkan.",
        "Tidak ada klaim cabang lokal; konsultasi tetap diarahkan ke showroom dan gudang Radja AC di Banyumas.",
      ],
      localFaqOverride: [
        [
          "AC rumah atau AC kos di Sumbang, hemat listrik?",
          "Rumah dan kos dengan daya 900–1300 watt banyak pakai low watt agar listrik tidak turun. Sebutkan daya dan ukuran kamar untuk cek unit dan stok.",
        ],
        [
          "Sumbang agak ke arah Baturraden, semua area perlu AC?",
          "Tidak selalu. Area bawah yang panas saat siang yang paling butuh AC; sisi atas yang lebih sejuk biasanya selektif per kamar. Sebutkan lokasi untuk masukan.",
        ],
        [
          "Karena dekat Banyumas, pengiriman ke Sumbang cepat?",
          "Relatif mudah. Sumbang masih dekat basis layanan, jadi pengiriman unit dan survei lokasi gampang dijadwalkan. Sebutkan alamat dan jumlah unit.",
        ],
        [
          "Pembayaran AC di Sumbang bisa DP atau transfer?",
          "Bisa. Banyak pembeli ambil DP dulu lalu pelunasan transfer atau COD saat unit datang dan stok dipastikan.",
        ],
      ],
      relatedLinksOverride: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Kembaran", routes.jualAcKembaran],
        ["Jual AC Baturraden", routes.jualAcBaturraden],
        ["Katalog AC", routes.katalog],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Kontak Radja AC", routes.kontak],
      ],
    },
  {
      slug: "jual-ac-kedungbanteng",
      path: routes.jualAcKedungbanteng,
      areaName: "Kedungbanteng",
      localContext:
        "Kedungbanteng ada di ring utara-barat Purwokerto, perbukitan dekat hutan pendidikan UNSOED dan sisi menuju Baturraden, dengan udara yang lebih segar di bagian atas. Pembeli AC banyak dari rumah tinggal, villa dan homestay kecil, properti sewa, serta toko dan usaha lokal. Penginapan kecil biasanya pasang AC di kamar tamu, sedangkan rumah cukup di kamar tertentu. Untuk jual AC Kedungbanteng, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      localLandmarks: [
        "Hutan pendidikan dan wisata UNSOED",
        "Jalur Kedungbanteng menuju Baturraden/Karanglewas",
        "Kawasan villa dan homestay kecil",
        "Pasar dan permukiman Kedungbanteng",
        "Perbukitan dan persawahan",
      ],
      localBenefits: [
        "Villa, homestay, dan properti sewa pasang AC di kamar tamu yang perlu nyaman saat ada tamu",
        "Rumah biasanya cukup AC di kamar tertentu karena udara sebagian sudah segar",
        "Masih dekat Banyumas sehingga pengiriman unit dan survei lokasi mudah dijadwalkan",
      ],
      localCases: [
        ["Villa & homestay kecil", "Pemasangan AC kamar tamu dengan unit yang mudah dirawat saat okupansi naik."],
        ["Rumah tinggal", "AC kamar tertentu yang panas, bukan seluruh rumah, karena sebagian area sudah segar."],
        ["Properti sewa & usaha", "Pemilihan unit untuk kamar sewa atau ruang usaha, dikirim ke alamat lalu dipasang."],
      ],
      label: "Jual AC Kedungbanteng",
      title: "Jual AC Kedungbanteng untuk Rumah, Villa & Usaha — Radja AC",
      description:
        "Butuh AC untuk rumah, villa, homestay, toko, kantor kecil, atau usaha di Kedungbanteng? Radja AC cek PK, stok, pengiriman, dan opsi pemasangan.",
      h1: "Jual AC Kedungbanteng untuk Rumah, Villa & Usaha",
      eyebrow: "Area Banyumas Utara-Barat",
      intro:
        "Butuh AC di Kedungbanteng untuk rumah, villa, homestay kecil, toko, kantor kecil, atau usaha lokal? Tim Radja AC membantu cek ukuran ruangan, daya listrik, stok, pilihan brand, pengiriman, dan opsi pemasangan dari data awal.",
      parentAreaName: "Banyumas",
      parentAreaPath: routes.jualAcBanyumas,
      priority: "P1",
      localAngle:
        "Kedungbanteng dekat dengan Purwokerto utara-barat sehingga relevan sebagai child area Banyumas yang masih dekat basis layanan.",
      nearbyAreaLinks: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Karanglewas", routes.jualAcKaranglewas],
        ["Jual AC Baturraden", routes.jualAcBaturraden],
      ],
      keywordVariantsOverride: [
        "jual AC Kedungbanteng",
        "AC rumah Kedungbanteng",
        "AC villa Kedungbanteng",
        "AC toko Kedungbanteng",
        "AC kantor kecil Kedungbanteng",
        "cek stok AC Kedungbanteng",
        "pengiriman AC Kedungbanteng",
        "opsi pemasangan AC Kedungbanteng",
        "AC banyak unit Kedungbanteng",
      ],
      commonNeedsOverride: [
        "AC rumah tinggal, kamar tidur, dan ruang keluarga area Kedungbanteng",
        "AC untuk villa, homestay, guest house kecil, atau properti sewa sekitar jalur utara Purwokerto",
        "AC toko, ruko kecil, kantor kecil, dan ruang usaha lokal",
        "Pembelian beberapa unit untuk rumah besar, usaha, penginapan kecil, atau kebutuhan bertahap",
      ],
      buyingChecksOverride: [
        "Alamat detail Kedungbanteng dan akses lokasi dari arah Purwokerto/Banyumas",
        "Ukuran ruangan, tinggi plafon, sirkulasi, dan kondisi panas sekitar bangunan",
        "Daya listrik, pilihan low watt/inverter, dan durasi pemakaian harian",
        "Jumlah unit, preferensi brand, anggaran, dan kebutuhan pengiriman atau opsi pemasangan",
      ],
      trustBulletsOverride: [
        "Kedungbanteng diposisikan sebagai ring utara-barat Purwokerto yang dekat dengan Baturraden dan Karanglewas.",
        "Cocok untuk kebutuhan rumah, usaha lokal, properti sewa, dan beberapa unit dengan pengecekan PK lebih dulu.",
        "Stok, pengiriman, dan opsi pemasangan dikonfirmasi berdasarkan data lokasi dan jumlah unit.",
        "Tidak ada klaim showroom lokal; bukti operasional tetap mengacu ke Radja AC Banyumas.",
      ],
      localFaqOverride: [
        [
          "Kedungbanteng agak sejuk, perlu AC di semua ruangan?",
          "Tidak selalu. Sebagian area atas sudah segar, jadi AC biasanya dipasang di kamar atau ruang tertentu yang panas, atau di kamar tamu penginapan. Sebutkan lokasi dan ruangannya.",
        ],
        [
          "Cocok untuk villa, homestay, atau properti sewa di Kedungbanteng?",
          "Cocok. Penginapan kecil biasanya pasang AC kamar tamu dengan unit yang mudah dirawat. Kirim jumlah kamar dan ukurannya untuk arahan unit dan stok.",
        ],
        [
          "Karena dekat Banyumas, pengiriman ke Kedungbanteng cepat?",
          "Relatif mudah. Masih dekat basis layanan, jadi pengiriman unit dan survei lokasi gampang dijadwalkan. Sebutkan alamat dan jumlah unit.",
        ],
        [
          "Pembayaran AC di Kedungbanteng bisa DP atau transfer?",
          "Bisa. Banyak pembeli ambil DP dulu lalu pelunasan transfer atau COD saat unit datang dan stok dipastikan.",
        ],
      ],
      relatedLinksOverride: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Karanglewas", routes.jualAcKaranglewas],
        ["Jual AC Baturraden", routes.jualAcBaturraden],
        ["AC Inverter", routes.katalogAcInverter],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Kontak Radja AC", routes.kontak],
      ],
    },
  {
      slug: "jual-ac-kalibagor",
      path: routes.jualAcKalibagor,
      areaName: "Kalibagor",
      localContext:
        "Kalibagor ada di jalur Banyumas–Sokaraja, daerah dagang dan pertanian dengan jejak bekas Pabrik Gula Kalibagor. Karena posisinya dekat basis layanan Radja AC di Sokaraja, pengiriman unit dan survei lokasi relatif mudah. Pembeli AC di sini umumnya rumah, toko, dan kantor desa yang gerah saat siang. Untuk jual AC Kalibagor, unit diantar ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      localLandmarks: [
        "Bekas Pabrik Gula Kalibagor",
        "Jalur Banyumas–Sokaraja",
        "Pasar Kalibagor",
        "Aliran Sungai Serayu",
        "Dekat basis layanan Radja AC di Sokaraja",
      ],
      localBenefits: [
        "Dekat basis layanan di Sokaraja sehingga pengiriman unit dan survei lokasi gampang dijadwalkan",
        "Toko dan ruko di jalur Banyumas–Sokaraja butuh ruang yang adem buat pembeli",
        "AC rumah banyak pilih low watt menyesuaikan daya listrik rumahan",
      ],
      localCases: [
        ["Rumah tinggal", "Pemasangan AC kamar yang panas saat siang; survei mudah karena dekat Sokaraja."],
        ["Toko & ruko jalur", "AC ruang jualan di jalur Banyumas–Sokaraja agar pembeli betah."],
        ["Kantor kecil & usaha", "Pemilihan unit ruang kerja dengan pengiriman cepat ke alamat Kalibagor."],
      ],
      label: "Jual AC Kalibagor",
      title: "Jual AC Kalibagor untuk Rumah, Toko & Usaha — Radja AC",
      description:
        "Butuh AC untuk rumah, toko, kantor kecil, ruko, atau usaha di Kalibagor? Radja AC cek kebutuhan PK, stok, pengiriman unit, dan opsi pemasangan via WhatsApp.",
      h1: "Jual AC Kalibagor untuk Rumah, Toko & Usaha",
      eyebrow: "Jalur Banyumas - Sokaraja",
      intro:
        "Butuh AC di Kalibagor untuk rumah, toko, kantor kecil, ruko, atau usaha? Tim Radja AC cek ukuran ruangan, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan sebelum pembelian.",
      parentAreaName: "Banyumas",
      parentAreaPath: routes.jualAcBanyumas,
      priority: "P1",
      localAngle:
        "Kalibagor berada di jalur Banyumas-Sokaraja sehingga cocok sebagai child area yang menguatkan sisi timur/selatan Banyumas.",
      nearbyAreaLinks: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Sokaraja", routes.jualAcSokaraja],
        ["Jual AC Kembaran", routes.jualAcKembaran],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
      ],
      keywordVariantsOverride: [
        "jual AC Kalibagor",
        "AC rumah Kalibagor",
        "AC toko Kalibagor",
        "AC kantor kecil Kalibagor",
        "AC usaha Kalibagor",
        "cek stok AC Kalibagor",
        "pengiriman AC Kalibagor",
        "opsi pemasangan AC Kalibagor",
        "AC banyak unit Kalibagor",
      ],
      commonNeedsOverride: [
        "AC rumah tinggal, kamar tidur, dan ruang keluarga area Kalibagor",
        "AC toko, warung, ruko kecil, kantor kecil, klinik ringan, dan ruang usaha",
        "AC untuk bangunan keluarga atau beberapa ruangan di jalur Banyumas-Sokaraja",
        "Pembelian beberapa unit untuk usaha lokal, properti sewa, atau kebutuhan bertahap",
      ],
      buyingChecksOverride: [
        "Alamat detail Kalibagor dan kedekatan akses ke Banyumas/Sokaraja",
        "Ukuran ruangan, tinggi plafon, arah panas, dan jumlah orang di ruangan",
        "Daya listrik, pilihan standard/low watt/inverter, dan jam pemakaian",
        "Jumlah unit, preferensi brand, target anggaran, pengiriman, dan kebutuhan opsi pemasangan",
      ],
      trustBulletsOverride: [
        "Kalibagor diposisikan sebagai child area jalur Banyumas-Sokaraja.",
        "Kebutuhan AC cocok dimulai dari cek ukuran ruangan, daya listrik, stok aktif, dan pilihan brand.",
        "Pengiriman serta opsi pemasangan dikonfirmasi berdasarkan alamat detail dan kondisi lokasi.",
        "Konsultasi tetap diarahkan ke Radja AC Banyumas tanpa klaim toko/cabang lokal.",
      ],
      localFaqOverride: [
        [
          "Kalibagor dekat showroom Sokaraja, pengirimannya cepat?",
          "Karena Kalibagor di jalur Banyumas-Sokaraja dan dekat basis layanan, pengiriman unit dan survei lokasi relatif mudah dijadwalkan. Sebutkan alamat dan jumlah unit untuk perkiraan.",
        ],
        [
          "AC rumah di Kalibagor, hemat listrik?",
          "Rumah dengan daya 900-1300 watt banyak pakai low watt agar listrik tidak turun. Sebutkan daya listrik dan ukuran kamar untuk cek unit dan stok.",
        ],
        [
          "AC untuk toko atau ruko di jalur Kalibagor, pilih apa?",
          "Ruang jualan yang ramai dan pintunya sering kebuka butuh kapasitas sesuai luas. Sebutkan ukuran toko dan jam buka untuk cek unit.",
        ],
        [
          "Pembayaran AC di Kalibagor bisa DP atau transfer?",
          "Bisa. Banyak pembeli ambil DP dulu lalu pelunasan transfer atau COD saat unit datang dan stok dipastikan.",
        ],
      ],
      relatedLinksOverride: [
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Sokaraja", routes.jualAcSokaraja],
        ["Jual AC Kembaran", routes.jualAcKembaran],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["AC 1/2 PK", routes.katalogAcSetengahPk],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Kontak Radja AC", routes.kontak],
      ],
    },
];
