import { routes } from "@/content/routes";

export const cilacapAreas = [
  {
      slug: "jual-ac-cilacap",
      path: routes.jualAcCilacap,
      areaName: "Cilacap",
      localLandmarks: [
        "Kilang minyak Pertamina Cilacap",
        "Pelabuhan Tanjung Intan",
        "Kawasan industri dan pergudangan",
        "Pantai Teluk Penyu dan Benteng Pendem",
        "Permukiman pesisir yang panas dan lembap",
      ],
      localBenefits: [
        "Kantor perusahaan dan proyek industri sering butuh pengadaan AC banyak unit dengan spesifikasi seragam, faktur, dan jadwal pemasangan",
        "Udara pesisir yang asin dan lembap mempercepat karat pada unit outdoor, jadi pemilihan unit dan penempatannya diperhatikan",
        "Rumah, ruko, dan kantor di Cilacap cari unit yang cepat dingin di cuaca panas pesisir",
      ],
      localCases: [
        ["Kantor perusahaan & proyek industri", "Pengadaan AC banyak unit untuk kantor dan proyek dengan faktur serta jadwal pemasangan bertahap."],
        ["Ruko & toko pesisir", "AC ruang usaha yang cepat dingin; penempatan outdoor diperhatikan karena udara asin."],
        ["Rumah tinggal", "Pengiriman unit per kecamatan lalu pemasangan, dengan pilihan unit untuk cuaca lembap."],
      ],
      label: "Jual AC Cilacap",
      title: "Jual AC Cilacap | Industri, Pesisir & Pengadaan Proyek — Radja AC",
      description:
        "Beli AC untuk rumah, kantor, proyek industri, atau banyak unit di Cilacap? Radja AC cek PK, stok, pengiriman, dan opsi pemasangan via WhatsApp.",
      h1: "Jual AC Cilacap — rumah, kantor, proyek industri, dan pengadaan banyak unit",
      eyebrow: "Layanan AC Area Cilacap",
      intro:
        "Butuh AC di Cilacap untuk rumah, toko, kantor, usaha, proyek, pengadaan, atau banyak unit? Tim Radja AC membantu cek kebutuhan PK, daya listrik, pilihan brand, stok unit, pengiriman, dan opsi pemasangan berdasarkan kecamatan serta kebutuhan unit.",
      localContext:
        "Cilacap adalah kota industri dan pelabuhan—ada kilang Pertamina, pabrik semen, PLTU, dan Pelabuhan Tanjung Intan—dengan udara pesisir yang panas dan lembap. Karena itu permintaan terbesar datang dari kantor perusahaan, vendor dan kontraktor proyek, ruko, dan rumah; banyak yang butuh pengadaan AC banyak unit dengan faktur dan jadwal. Udara pesisir yang asin juga membuat unit outdoor lebih cepat berkarat, sehingga pemilihan dan penempatan unit jadi pertimbangan. Untuk jual AC Cilacap, pengiriman dan pemasangan dikonfirmasi per kecamatan, dengan pembayaran DP, transfer, atau termin untuk proyek.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Cilacap dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan yang dikonfirmasi berdasarkan alamat, jumlah unit, akses lokasi, stok, dan jadwal pekerjaan.",
      commonNeeds: [
        "AC rumah tinggal, kamar tidur, dan ruang keluarga di Cilacap",
        "AC toko, ruko, kantor, klinik, dan ruang usaha",
        "AC untuk beberapa ruangan, banyak titik, atau bangunan usaha",
        "Pengadaan unit untuk usaha, kantor, proyek, dan kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Kecamatan atau area detail pengiriman di Cilacap",
        "Ukuran ruangan, tinggi plafon, dan jumlah unit yang dibutuhkan",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Kebutuhan unit saja, pengiriman, atau opsi pemasangan sesuai alamat",
      ],
      paymentNote:
        "Pembayaran fleksibel bisa dikonsultasikan: DP, COD, atau transfer setelah kebutuhan unit, alamat, pengiriman, dan opsi pemasangan jelas.",
      relatedLinks: [
        ["Jual AC Kroya", routes.jualAcKroya],
        ["Jual AC Majenang", routes.jualAcMajenang],
        ["Jual AC Sidareja", routes.jualAcSidareja],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Kantor & Komersial", routes.katalogAcKantorKomersial],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["Pengadaan AC Proyek", routes.pengadaanAc],
        ["AC Daikin", routes.brandDaikin],
        ["AC Gree", routes.brandGree],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Tentang Radja AC", routes.tentangKami],
        ["Kontak Radja AC", routes.kontak],
        ["Memilih AC untuk Daerah Pesisir", routes.artikelMemilihAcUntukDaerahPesisir],
      ],
      ctaLabel: "Chat WhatsApp untuk cek pengiriman AC Cilacap",
      waIntent: "cek pengiriman dan stok AC Cilacap dengan data kecamatan ukuran ruangan daya listrik jumlah unit alamat dan kebutuhan pemasangan",
      waArea: "Cilacap",
      keywordVariants: [
        "jual AC Cilacap",
        "toko AC Cilacap",
        "beli AC Cilacap",
        "AC kantor Cilacap",
        "AC proyek industri Cilacap",
        "pengadaan AC pabrik Cilacap",
        "AC pesisir tahan korosi Cilacap",
        "AC rumah Cilacap",
        "pasang AC Cilacap",
        "ganti AC lama Cilacap",
        "AC banyak unit Cilacap",
        "pengiriman AC Cilacap",
      ],
      nearbyAreaLinks: [
        ["Kroya", routes.jualAcKroya],
        ["Majenang", routes.jualAcMajenang],
        ["Sidareja", routes.jualAcSidareja],
        ["Kesugihan", routes.jualAcKesugihan],
        ["Adipala", routes.jualAcAdipala],
      ],
      trustBullets: [
        "Cilacap dilayani dari basis showroom dan gudang Radja AC di Banyumas.",
        "Kebutuhan AC dicek dari kecamatan, ukuran ruangan, daya listrik, jumlah unit, stok aktif, dan opsi pemasangan.",
        "Bukti aktivitas Radja AC bisa dicek melalui dokumentasi showroom, stok fisik, pengiriman, dan pemasangan.",
      ],
      localFaq: [
        [
          "Bisa pengadaan AC banyak unit untuk kantor atau proyek di Cilacap?",
          "Bisa. Sebutkan jumlah ruang atau titik, ukuran, dan target waktu; untuk pengadaan AC proyek unit disiapkan dengan spesifikasi seragam, faktur, dan jadwal pemasangan bertahap. Pembayaran bisa termin atau transfer.",
        ],
        [
          "Karena dekat laut, unit outdoor cepat karat — ada saran untuk Cilacap?",
          "Udara pesisir yang asin memang mempercepat korosi, jadi penempatan outdoor yang terlindung dan perawatan rutin membantu memperpanjang umur unit. Sebutkan lokasi pemasangan untuk masukan.",
        ],
        [
          "Melayani pengiriman AC ke kecamatan mana saja di Cilacap?",
          "Pengiriman dikonfirmasi per kecamatan—misalnya Cilacap kota, Kroya, Majenang, Sidareja—lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan kecamatan dan jumlah unit untuk perkiraan.",
        ],
        [
          "AC rumah atau ruko di Cilacap supaya cepat dingin di cuaca panas pesisir?",
          "Kapasitas dihitung dari luas, paparan panas, dan jumlah orang agar dingin merata. Sebutkan ukuran ruangan dan daya listrik untuk cek unit dan stok.",
        ],
        [
          "AC lama di rumah atau kantor Cilacap sudah tidak dingin padahal sudah sering dirawat, ganti atau servis lagi?",
          "Kalau unit sudah tua, sering kurang dingin, dan biaya servis terus keluar — apalagi di udara pesisir yang mempercepat kerusakan komponen — ganti baru lebih hemat. Kirim kondisi unit lama dan ukuran ruangan, tim Radja AC bantu hitung mana yang lebih masuk akal.",
        ],
        [
          "AC boros listrik di Cilacap, solusinya apa?",
          "AC lama yang boros biasanya karena kapasitas PK tidak sesuai ruangan atau komponen sudah aus. Ganti ke unit inverter baru yang sesuai PK jauh lebih hemat tagihan bulanan. Kirim ukuran ruangan dan daya listrik untuk rekomendasi unit.",
        ],
      ],
    },
  {
      slug: "jual-ac-kroya",
      path: routes.jualAcKroya,
      areaName: "Kroya",
      localLandmarks: [
        "Stasiun Kroya (simpul kereta jalur selatan Jawa)",
        "Pasar Kroya dan deretan ruko di jalan utama",
        "Pertigaan Buntu–Kroya–Cilacap (jalur lintas selatan)",
        "Kawasan kos dan hunian sekitar stasiun",
        "Pabrik dan gudang di koridor industri Kroya–Cilacap",
      ],
      localBenefits: [
        "Toko dan ruko di sekitar Stasiun dan Pasar Kroya yang ramai penumpang dan pembeli cepat gerah saat siang, sehingga AC ruang jualan jadi kebutuhan nyata bukan sekadar kenyamanan",
        "Kos dan hunian di sekitar stasiun banyak dihuni pekerja dan penumpang transit yang butuh kamar adem; low watt jadi pilihan agar daya per kamar aman",
        "Pabrik dan gudang di koridor Kroya–Cilacap kadang butuh pengadaan beberapa unit untuk ruang kerja dan kantor lapangan dengan jadwal yang mengikuti operasional",
      ],
      localCases: [
        ["Toko & ruko sekitar stasiun", "AC ruang jualan yang ramai penumpang dan pembeli agar betah; kapasitas dihitung dari luas dan lalu lalang."],
        ["Kos & hunian transit", "Pemasangan AC kamar dengan low watt agar daya per kamar aman saat banyak unit menyala."],
        ["Kantor & gudang industri", "Pemilihan unit ruang kerja dan kantor lapangan di koridor Kroya–Cilacap."],
      ],
      label: "Jual AC Kroya",
      title: "Jual AC Kroya | Toko Sekitar Stasiun, Kos Transit & Koridor Industri Cilacap — Radja AC",
      description:
        "AC untuk toko dan ruko sekitar Stasiun Kroya, kos pekerja transit, atau kantor di koridor industri Kroya–Cilacap? Radja AC cek PK, stok, dan pengiriman via WhatsApp.",
      h1: "Jual AC Kroya untuk Rumah, Toko & Usaha",
      eyebrow: "Area Cilacap",
      intro:
        "Butuh AC di Kroya untuk rumah, toko, ruko, kantor, usaha, atau banyak unit? Tim Radja AC cek kebutuhan PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan dari data awal yang dikirim.",
      localContext:
        "Kroya adalah simpul transit penting di jalur selatan Jawa—Stasiun Kroya melayani kereta lintas Jawa sehingga denyut ekonominya campuran antara dagang dan transit. Toko dan ruko di sekitar Pasar Kroya dan stasiun ramai penumpang dan pembeli, cepat gerah saat siang karena pintu sering terbuka. Kos dan hunian di sekitar stasiun banyak dihuni pekerja dan penumpang transit yang butuh kamar adem. Di koridor Kroya–Cilacap juga ada pabrik dan gudang yang kadang butuh pengadaan beberapa unit untuk ruang kerja. Untuk jual AC Kroya, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Kroya dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
      keywordVariants: [
        "AC rumah Kroya",
        "AC toko dan ruko Kroya",
        "AC kantor kecil Kroya",
        "AC usaha Kroya",
        "Banyak unit area Kroya",
        "Cek PK AC Kroya",
      ],
      nearbyAreaLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Jual AC Kesugihan", routes.jualAcKesugihan],
        ["Jual AC Adipala", routes.jualAcAdipala],
        ["Jual AC Sidareja", routes.jualAcSidareja],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
      ],
      trustBullets: [
        "Cek kebutuhan PK dari ukuran ruangan, daya listrik, dan pola pemakaian",
        "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
        "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Kroya dan jumlah unit",
        "Cocok untuk rumah, toko, ruko, kantor kecil, usaha, dan pembelian beberapa unit",
      ],
      localFaq: [
        [
          "AC untuk toko atau ruko di sekitar Stasiun Kroya yang ramai penumpang, pilih apa?",
          "Ruang yang ramai penumpang dan pintunya sering terbuka butuh kapasitas sedikit lebih besar dari kamar biasa agar dingin merata. Sebutkan ukuran toko dan jam ramai untuk cek unit dan stok.",
        ],
        [
          "Kos di sekitar Stasiun Kroya banyak penghuni, AC-nya bagaimana?",
          "Kos yang banyak kamarnya sebaiknya pakai low watt tipe seragam agar daya total bangunan tidak turun saat banyak unit menyala. Sebutkan jumlah kamar dan daya listrik total untuk arahan.",
        ],
        [
          "Bisa pengadaan beberapa unit untuk kantor atau gudang di koridor Kroya–Cilacap?",
          "Bisa. Sebutkan jumlah ruang, ukuran, dan target waktu; unit disiapkan dari stok lalu pengiriman dan pemasangan dijadwalkan mengikuti operasional. Pembayaran bisa DP atau transfer.",
        ],
        [
          "Bisa kirim dan pasang AC ke alamat di Kroya atau sekitar pertigaan Buntu?",
          "Bisa. Unit dikirim ke alamat di Kroya lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat dan jumlah unit untuk perkiraan pengiriman.",
        ],
      ],
      commonNeeds: [
        "AC rumah tinggal dan kamar tidur",
        "AC toko, ruko, kantor kecil, dan ruang usaha",
        "AC untuk beberapa ruangan atau beberapa titik",
        "Pembelian unit untuk usaha lokal dan kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Alamat detail area Kroya",
        "Ukuran ruangan dan estimasi kebutuhan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["Memilih AC untuk Daerah Pesisir", routes.artikelMemilihAcUntukDaerahPesisir],
        ["AC Inverter", routes.katalogAcInverter],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Kroya",
      waIntent: "cek stok AC Kroya dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Kroya",
    },
  {
      slug: "jual-ac-majenang",
      path: routes.jualAcMajenang,
      areaName: "Majenang",
      localLandmarks: [
        "Pasar Majenang dan deretan ruko di jalan utama",
        "Terminal Majenang dan jalur menuju Banjar/Bandung",
        "RSUD Majenang (rumah sakit umum daerah)",
        "Kawasan kos dan hunian sekitar pusat kota",
        "Jalur Majenang–Sidareja–Cilacap (lintas barat)",
      ],
      localBenefits: [
        "Ruko dan toko di Pasar Majenang yang jadi pusat dagang Cilacap barat ramai pembeli dari berbagai kecamatan, sehingga ruang jualan yang adem jadi daya tarik tersendiri",
        "RSUD Majenang dan klinik sekitarnya butuh ruang tunggu dan ruang periksa yang adem sepanjang jam operasional, bukan hanya saat ramai",
        "Majenang adalah titik terjauh dari gudang Banyumas di jalur barat, sehingga pengiriman dijadwalkan tersendiri dan pembeli perlu konfirmasi alamat detail lebih awal",
      ],
      localCases: [
        ["Ruko & toko Pasar Majenang", "AC ruang jualan di pusat dagang Cilacap barat agar pembeli dari berbagai kecamatan betah."],
        ["RSUD & klinik", "AC ruang tunggu dan ruang periksa yang dipakai seharian dengan kapasitas sesuai luas."],
        ["Rumah & kos", "Pemasangan AC kamar dengan pengiriman yang dijadwalkan tersendiri ke Cilacap barat."],
      ],
      label: "Jual AC Majenang",
      title: "Jual AC Majenang | Pasar Dagang Cilacap Barat, RSUD & Rumah — Radja AC",
      description:
        "AC untuk ruko di Pasar Majenang pusat dagang Cilacap barat, ruang tunggu RSUD Majenang, atau rumah? Radja AC bantu pilih unit, konfirmasi stok, dan jadwalkan pengiriman ke Cilacap barat.",
      h1: "Jual AC Majenang untuk Rumah, Toko & Banyak Unit",
      eyebrow: "Area Cilacap Barat",
      intro:
        "Butuh AC di Majenang untuk rumah, toko, kantor, usaha, atau kebutuhan beberapa unit? Tim Radja AC cek kapasitas PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan dari data awal.",
      localContext:
        "Majenang adalah kota dagang terbesar di Cilacap bagian barat, di jalur lintas menuju Banjar dan Bandung, dengan Pasar Majenang sebagai pusat ekonomi yang menarik pembeli dari berbagai kecamatan sekitarnya. RSUD Majenang dan klinik di sekitarnya juga jadi pusat layanan kesehatan untuk wilayah barat. Karena posisinya paling jauh dari gudang Radja AC di Banyumas di antara area Cilacap, pengiriman ke Majenang dijadwalkan tersendiri dan pembeli perlu konfirmasi alamat detail lebih awal. Untuk jual AC Majenang, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, transfer, atau COD setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Majenang dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
      keywordVariants: [
        "AC rumah Majenang",
        "AC toko Majenang",
        "AC kantor kecil Majenang",
        "AC usaha Majenang",
        "Banyak unit Majenang",
        "Cek PK AC Majenang",
      ],
      nearbyAreaLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Jual AC Sidareja", routes.jualAcSidareja],
        ["Jual AC Kroya", routes.jualAcKroya],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Jual AC Kebumen", routes.jualAcKebumen],
      ],
      trustBullets: [
        "Cek kebutuhan PK dari ukuran ruangan, fungsi bangunan, dan jam pemakaian",
        "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
        "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Majenang dan jumlah unit",
        "Cocok untuk rumah, toko, kantor kecil, usaha lokal, dan kebutuhan banyak unit",
      ],
      localFaq: [
        [
          "AC untuk ruko atau toko di Pasar Majenang yang jadi pusat dagang Cilacap barat?",
          "Ruang jualan yang ramai pembeli dari berbagai kecamatan dan pintunya sering terbuka butuh kapasitas sesuai luas dan lalu lalang. Sebutkan ukuran ruko dan jam buka untuk cek unit dan stok.",
        ],
        [
          "AC untuk ruang tunggu atau ruang periksa di RSUD atau klinik Majenang?",
          "Ruang layanan kesehatan yang dipakai seharian butuh kapasitas yang stabil, bukan yang termurah. Sebutkan ukuran ruang dan jam operasional untuk perkiraan PK dan stok.",
        ],
        [
          "Majenang paling jauh dari gudang Banyumas, pengirimannya bagaimana?",
          "Pengiriman ke Majenang dijadwalkan tersendiri karena jaraknya dari gudang Banyumas. Konfirmasi alamat detail dan jumlah unit lebih awal agar jadwal pengiriman dan pemasangan bisa disusun.",
        ],
        [
          "AC rumah di Majenang, pilih low watt atau inverter?",
          "Low watt cocok untuk rumah dengan daya 900–1300 watt agar MCB tidak turun; inverter lebih hemat untuk kamar yang AC-nya menyala hampir setiap malam. Sebutkan daya dan ukuran kamar untuk arahan yang lebih tepat.",
        ],
      ],
      commonNeeds: [
        "AC rumah tinggal dan kamar tidur",
        "AC toko, kantor kecil, dan ruang usaha",
        "AC untuk beberapa ruangan atau beberapa titik",
        "Pembelian banyak unit untuk usaha lokal",
      ],
      buyingChecks: [
        "Alamat detail area Majenang",
        "Ukuran ruangan dan estimasi kebutuhan PK",
        "Daya listrik dan kebutuhan low watt atau inverter",
        "Kebutuhan pengiriman dan opsi pemasangan",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["AC Kantor & Komersial", routes.katalogAcKantorKomersial],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Majenang",
      waIntent: "cek stok AC Majenang dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Majenang",
    },
  {
      slug: "jual-ac-sidareja",
      path: routes.jualAcSidareja,
      areaName: "Sidareja",
      localLandmarks: [
        "Stasiun Sidareja dan jalur kereta selatan",
        "Pasar Sidareja dan ruko di jalan utama kecamatan",
        "Kawasan rawa dan pertanian Sidareja (Rawa Besar)",
        "Jalur Sidareja–Majenang (lintas barat Cilacap)",
        "Permukiman warga di sekitar pasar dan stasiun",
      ],
      localBenefits: [
        "Ruko dan toko di sekitar Pasar Sidareja yang jadi titik belanja warga beberapa desa sekitar butuh ruang yang adem agar pembeli betah, terutama saat hari pasar ramai",
        "Rumah di permukiman sekitar rawa Sidareja terasa lembap dan gerah saat siang, sehingga AC kamar jadi kebutuhan yang lebih terasa dibanding daerah yang lebih kering",
        "Sidareja berada di antara Majenang dan Cilacap kota, sehingga pengiriman unit dijadwalkan tersendiri dan pembeli perlu konfirmasi alamat lebih awal",
      ],
      localCases: [
        ["Ruko & toko hari pasar", "AC ruang jualan di Pasar Sidareja agar pembeli dari desa sekitar betah saat hari pasar ramai."],
        ["Rumah sekitar rawa", "Pemasangan AC kamar yang terasa lembap dan gerah karena pengaruh rawa di sekitar permukiman."],
        ["Kantor & usaha", "Pemilihan unit ruang kerja dengan pengiriman yang dijadwalkan ke jalur barat Cilacap."],
      ],
      label: "Jual AC Sidareja",
      title: "Jual AC Sidareja | Ruko Pasar, Rumah Sekitar Rawa Besar & Jalur Barat Cilacap — Radja AC",
      description:
        "AC untuk ruko di Pasar Sidareja, rumah yang lembap karena Rawa Besar, atau usaha jalur barat Cilacap? Radja AC rekomendasikan PK sesuai kondisi lembap dan atur pengiriman ke Sidareja.",
      h1: "Jual AC Sidareja untuk Rumah, Ruko & Usaha",
      eyebrow: "Area Cilacap Barat",
      intro:
        "Butuh AC di Sidareja untuk rumah, ruko, toko, kantor, usaha, atau kebutuhan beberapa unit? Tim Radja AC cek kebutuhan PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan dari data awal.",
      localContext:
        "Sidareja adalah kota kecamatan di Cilacap bagian barat yang dikelilingi kawasan rawa dan pertanian—termasuk Rawa Besar—dengan Stasiun Sidareja dan Pasar Sidareja sebagai pusat kegiatan. Karena dikelilingi rawa, udara di permukiman sekitar terasa lebih lembap dan gerah saat siang dibanding daerah yang lebih kering, sehingga AC kamar jadi kebutuhan yang lebih terasa. Ruko dan toko di sekitar pasar ramai saat hari pasar karena pembeli datang dari beberapa desa sekitar. Posisi Sidareja di antara Majenang dan Cilacap kota membuat pengiriman dijadwalkan tersendiri. Untuk jual AC Sidareja, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Sidareja dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
      keywordVariants: [
        "AC rumah Sidareja",
        "AC ruko Sidareja",
        "AC toko Sidareja",
        "AC kantor Sidareja",
        "AC usaha Sidareja",
        "Cek PK AC Sidareja",
      ],
      nearbyAreaLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Jual AC Majenang", routes.jualAcMajenang],
        ["Jual AC Kroya", routes.jualAcKroya],
        ["Jual AC Kesugihan", routes.jualAcKesugihan],
        ["Jual AC Kebumen", routes.jualAcKebumen],
      ],
      trustBullets: [
        "Cek kebutuhan PK dari ukuran ruangan, fungsi bangunan, dan daya listrik",
        "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
        "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Sidareja dan jumlah unit",
        "Cocok untuk rumah, ruko, toko, kantor kecil, ruang usaha, dan beberapa unit",
      ],
      localFaq: [
        [
          "Rumah di Sidareja dekat rawa terasa lembap dan gerah, AC apa yang cocok?",
          "Udara lembap dari rawa membuat ruangan terasa lebih gerah, jadi kapasitas PK perlu dihitung dari luas dan kondisi lembap tersebut, bukan sekadar ukuran standar. Sebutkan ukuran kamar dan kondisi sekitar untuk arahan yang lebih tepat.",
        ],
        [
          "AC untuk ruko atau toko di Pasar Sidareja saat hari pasar ramai?",
          "Hari pasar membuat toko lebih ramai dari biasanya; kapasitas dihitung dari luas dan jumlah pengunjung puncak. Sebutkan ukuran toko dan hari pasar untuk cek unit dan stok.",
        ],
        [
          "Sidareja di antara Majenang dan Cilacap kota, pengirimannya bagaimana?",
          "Pengiriman ke Sidareja dijadwalkan tersendiri karena posisinya di jalur barat. Konfirmasi alamat detail dan jumlah unit lebih awal agar jadwal pengiriman dan pemasangan bisa disusun.",
        ],
        [
          "AC rumah di Sidareja, daya listrik terbatas, pilih apa?",
          "Rumah dengan daya 900–1300 watt banyak pakai low watt agar MCB tidak turun. Sebutkan daya dan ukuran kamar untuk cek unit dan stok yang sesuai.",
        ],
      ],
      commonNeeds: [
        "AC rumah tinggal dan kamar tidur",
        "AC ruko, toko, kantor kecil, dan ruang usaha",
        "AC untuk beberapa ruangan atau beberapa titik",
        "Pembelian unit untuk usaha lokal dan kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Alamat detail area Sidareja",
        "Ukuran ruangan dan estimasi kebutuhan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Split Rumah", routes.katalogAcSplitRumah],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Sidareja",
      waIntent: "cek stok AC Sidareja dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Sidareja",
    },
  {
      slug: "jual-ac-kesugihan",
      path: routes.jualAcKesugihan,
      areaName: "Kesugihan",
      localLandmarks: [
        "Pondok Pesantren Al-Ihya Ulumaddin (Kesugihan)",
        "Kawasan industri Cilacap (koridor Kesugihan–Cilacap kota)",
        "Asrama santri dan kos sekitar pesantren",
        "Pasar Kesugihan dan permukiman warga",
        "Jalur Kesugihan–Cilacap kota (jalan nasional)",
      ],
      localBenefits: [
        "Pondok Pesantren Al-Ihya Ulumaddin punya ratusan santri dengan asrama dan ruang belajar; ruang kelas dan aula yang dipakai seharian butuh pendinginan yang berbeda dari kamar kos biasa",
        "Asrama dan kos santri dengan banyak kamar kecil cari AC low watt tipe seragam agar daya total bangunan tidak turun dan perawatan antar kamar lebih mudah",
        "Kantor dan usaha di koridor Kesugihan–Cilacap yang dekat kawasan industri butuh unit yang cepat dingin dan tahan dipakai seharian di udara panas",
      ],
      localCases: [
        ["Ruang kelas & aula pesantren", "AC ruang belajar dan aula Al-Ihya Ulumaddin yang dipakai seharian; kapasitas dihitung dari luas dan jumlah santri."],
        ["Asrama & kos santri", "AC banyak kamar kecil dengan low watt tipe seragam agar daya total bangunan aman dan perawatan mudah."],
        ["Kantor & usaha koridor industri", "Pemilihan unit ruang kerja di jalur Kesugihan–Cilacap yang dekat kawasan industri."],
      ],
      label: "Jual AC Kesugihan",
      title: "Jual AC Kesugihan | Pesantren Al-Ihya Ulumaddin, Asrama Santri & Industri — Radja AC",
      description:
        "AC ruang kelas dan asrama Pesantren Al-Ihya Ulumaddin Kesugihan, atau kantor di koridor industri Cilacap? Radja AC cek PK, stok, dan pengiriman via WhatsApp.",
      h1: "Jual AC Kesugihan untuk Rumah, Kantor & Proyek",
      eyebrow: "Area Cilacap",
      intro:
        "Butuh AC di Kesugihan untuk rumah, asrama, kantor, ruang usaha, proyek, atau kebutuhan beberapa unit? Tim Radja AC cek kebutuhan PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan berdasarkan data awal.",
      localContext:
        "Kesugihan berada di jalur Cilacap menuju kota, dikenal dengan Pondok Pesantren Al-Ihya Ulumaddin—salah satu pesantren besar di Cilacap—yang punya ratusan santri dengan asrama, ruang kelas, dan aula. Kebutuhan AC di sini beragam: ruang kelas dan aula yang dipakai seharian butuh kapasitas yang dihitung dari luas dan jumlah santri, sedangkan asrama dan kos santri butuh unit low watt tipe seragam agar daya total bangunan tidak turun. Di sisi lain, kantor dan usaha di koridor Kesugihan–Cilacap yang dekat kawasan industri butuh unit yang cepat dingin. Untuk jual AC Kesugihan, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, transfer, atau COD setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Kesugihan dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
      keywordVariants: [
        "AC rumah Kesugihan",
        "AC kantor Kesugihan",
        "AC ruang usaha Kesugihan",
        "AC proyek Kesugihan",
        "Banyak unit Kesugihan",
        "Cek PK AC Kesugihan",
      ],
      nearbyAreaLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Jual AC Kroya", routes.jualAcKroya],
        ["Jual AC Adipala", routes.jualAcAdipala],
        ["Jual AC Sidareja", routes.jualAcSidareja],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
      ],
      trustBullets: [
        "Cek kebutuhan PK dari ukuran ruangan, fungsi bangunan, dan target pemakaian",
        "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
        "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Kesugihan dan jumlah unit",
        "Cocok untuk rumah, kantor, ruang usaha, proyek kecil, dan kebutuhan banyak unit",
      ],
      localFaq: [
        [
          "AC untuk ruang kelas atau aula di Pesantren Al-Ihya Ulumaddin Kesugihan, pilih apa?",
          "Ruang kelas dan aula yang dipakai seharian dengan banyak santri butuh kapasitas yang dihitung dari luas dan jumlah orang, bukan sekadar ukuran kamar biasa. Sebutkan ukuran ruang dan jumlah santri untuk perkiraan PK dan stok.",
        ],
        [
          "AC untuk asrama atau kos santri banyak kamar di Kesugihan, hemat listrik?",
          "Untuk banyak kamar kecil, low watt tipe seragam menjaga daya total bangunan dan memudahkan perawatan antar kamar. Sebutkan jumlah kamar dan daya listrik total untuk cek unit dan stok.",
        ],
        [
          "Bisa pengadaan beberapa unit untuk kantor atau usaha di koridor Kesugihan–Cilacap?",
          "Bisa. Sebutkan jumlah ruang, ukuran, dan target waktu; unit disiapkan dari stok lalu pengiriman dan pemasangan dijadwalkan. Pembayaran bisa DP atau transfer.",
        ],
        [
          "Bisa kirim dan pasang AC ke alamat di Kesugihan atau sekitar pesantren?",
          "Bisa. Unit dikirim ke alamat di Kesugihan lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat detail dan jumlah unit untuk perkiraan pengiriman.",
        ],
      ],
      commonNeeds: [
        "AC rumah tinggal dan ruang keluarga",
        "AC kantor kecil, ruang usaha, dan ruang kerja",
        "AC untuk beberapa ruangan atau beberapa titik",
        "Pembelian unit untuk proyek kecil dan kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Alamat detail area Kesugihan",
        "Ukuran ruangan dan estimasi kebutuhan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Kantor & Komersial", routes.katalogAcKantorKomersial],
        ["Pengadaan AC Proyek", routes.pengadaanAc],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Kesugihan",
      waIntent: "cek stok AC Kesugihan dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Kesugihan",
    },
  {
      slug: "jual-ac-adipala",
      path: routes.jualAcAdipala,
      areaName: "Adipala",
      localLandmarks: [
        "PLTU Adipala (Pembangkit Listrik Tenaga Uap)",
        "Pantai Widarapayung dan Pantai Jetis (pesisir selatan Adipala)",
        "Pasar Adipala dan permukiman nelayan",
        "Kawasan tambak dan pertanian pesisir",
        "Jalur Adipala–Kroya–Cilacap kota",
      ],
      localBenefits: [
        "Kontraktor, vendor, dan kantor lapangan di sekitar PLTU Adipala kadang butuh pengadaan beberapa unit AC untuk ruang kerja dan mess dengan spesifikasi yang bisa dilengkapi faktur",
        "Rumah dan toko di permukiman pesisir Adipala yang panas dan lembap butuh AC yang cepat mendinginkan ruangan; udara asin dari laut membuat penempatan outdoor perlu diperhatikan agar tidak cepat berkarat",
        "Nelayan dan pelaku usaha tambak yang membangun rumah atau warung di pesisir Adipala sering cari unit yang tahan dipakai di lingkungan lembap dengan perawatan yang tidak rumit",
      ],
      localCases: [
        ["Kantor & mess sekitar PLTU", "Pengadaan AC ruang kerja dan mess untuk kontraktor atau vendor proyek pembangkit, bisa dilengkapi faktur."],
        ["Rumah & warung nelayan pesisir", "AC kamar dan ruang usaha di permukiman nelayan Adipala; penempatan outdoor diperhatikan karena udara asin."],
        ["Toko & usaha jalur Adipala–Kroya", "AC ruang jualan di jalur utama agar pembeli betah di cuaca panas pesisir."],
      ],
      label: "Jual AC Adipala",
      title: "Jual AC Adipala | PLTU, Nelayan Pantai Widarapayung & Toko Pesisir — Radja AC",
      description:
        "AC untuk mess kontraktor PLTU Adipala, rumah nelayan di Pantai Widarapayung, atau toko pesisir yang panas? Radja AC cek PK, stok, dan pengiriman via WhatsApp.",
      h1: "Jual AC Adipala untuk Rumah, Toko & Usaha",
      eyebrow: "Area Cilacap",
      intro:
        "Butuh AC di Adipala untuk rumah, toko, kantor, usaha, atau kebutuhan beberapa unit? Tim Radja AC cek kebutuhan PK, daya listrik, stok brand, pengiriman, dan opsi pemasangan berdasarkan kondisi ruangan.",
      localContext:
        "Adipala adalah kecamatan pesisir di Cilacap yang dikenal dengan PLTU Adipala—pembangkit listrik tenaga uap yang jadi salah satu infrastruktur energi penting di Jawa Tengah—serta pantai selatan seperti Pantai Widarapayung dan Pantai Jetis. Permukiman nelayan dan pelaku usaha tambak tersebar di sepanjang pesisir, dengan udara panas dan lembap yang membuat ruangan cepat gerah. Kontraktor dan vendor sekitar PLTU kadang butuh pengadaan beberapa unit AC untuk ruang kerja dan mess. Karena dekat laut, udara asin mempercepat korosi pada unit outdoor sehingga penempatan perlu diperhatikan sejak awal. Untuk jual AC Adipala, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC berada di Banyumas. Kebutuhan AC area Adipala dilayani dengan konsultasi PK, cek stok unit, pengiriman, serta opsi pemasangan sesuai alamat, jumlah unit, dan jadwal.",
      keywordVariants: [
        "AC rumah Adipala",
        "AC toko Adipala",
        "AC kantor kecil Adipala",
        "AC usaha Adipala",
        "AC ruangan panas Adipala",
        "Cek PK AC Adipala",
      ],
      nearbyAreaLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Jual AC Kroya", routes.jualAcKroya],
        ["Jual AC Kesugihan", routes.jualAcKesugihan],
        ["Jual AC Sidareja", routes.jualAcSidareja],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
      ],
      trustBullets: [
        "Cek kebutuhan PK dari ukuran ruangan, paparan panas, daya listrik, dan pola pemakaian",
        "Cek stok brand seperti Gree, Daikin, Midea, Hisense, Sharp, Samsung, dan lainnya",
        "Opsi pengiriman dan pemasangan dikonfirmasi berdasarkan alamat Adipala dan jumlah unit",
        "Cocok untuk rumah, toko, kantor kecil, usaha, dan ruangan yang terasa panas",
      ],
      localFaq: [
        [
          "Bisa pengadaan AC untuk kantor lapangan atau mess kontraktor di sekitar PLTU Adipala?",
          "Bisa. Untuk pengadaan ruang kerja dan mess, sebutkan jumlah ruang, ukuran, dan target waktu; unit disiapkan dari stok, bisa dilengkapi faktur, lalu pengiriman dan pemasangan dijadwalkan mengikuti operasional proyek.",
        ],
        [
          "Rumah atau warung nelayan di pesisir Adipala, unit outdoor-nya aman dari korosi?",
          "Udara asin dari laut memang mempercepat korosi pada unit outdoor. Penempatan yang terlindung dari angin laut langsung dan perawatan rutin membantu memperpanjang umur unit. Sebutkan lokasi pemasangan untuk masukan lebih spesifik.",
        ],
        [
          "AC untuk toko atau warung di jalur Adipala–Kroya yang panas, pilih apa?",
          "Ruang usaha di jalur pesisir yang panas dan lembap butuh kapasitas sesuai luas dan paparan panas. Sebutkan ukuran ruang dan jam buka untuk cek unit dan stok yang sesuai.",
        ],
        [
          "Bisa kirim dan pasang AC ke permukiman nelayan atau tambak di Adipala?",
          "Bisa. Unit dikirim ke alamat di Adipala lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat detail dan jumlah unit untuk perkiraan pengiriman.",
        ],
      ],
      commonNeeds: [
        "AC rumah tinggal dan kamar tidur",
        "AC toko, kantor kecil, dan ruang usaha",
        "AC untuk ruangan yang panas atau sering dipakai",
        "Pembelian unit untuk usaha lokal dan beberapa titik",
      ],
      buyingChecks: [
        "Alamat detail area Adipala",
        "Ukuran ruangan, paparan panas, dan estimasi kebutuhan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Kebutuhan unit saja, pengiriman, atau opsi pemasangan",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["AC Inverter", routes.katalogAcInverter],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
        ["Memilih AC untuk Daerah Pesisir", routes.artikelMemilihAcUntukDaerahPesisir],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Adipala",
      waIntent: "cek stok AC Adipala dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Adipala",
    },
];
