import { routes } from "@/content/routes";

export const cilacapAreas = [
  {
      slug: "jual-ac-cilacap",
      path: routes.jualAcCilacap,
      areaName: "Cilacap",
      localLandmarks: [
        "Cilacap kota",
        "Kroya",
        "Majenang",
        "Sidareja",
        "Kesugihan",
        "Adipala",
        "Area pesisir dan kawasan industri",
      ],
      localBenefits: [
        "Rumah dan ruko di Cilacap butuh AC yang cepat dingin, tapi tetap aman untuk daya listrik harian.",
        "Area pesisir bikin unit outdoor lebih cepat kena karat, jadi posisi outdoor perlu dicek sebelum pasang.",
        "Kantor, toko, dan proyek bisa cek stok banyak unit, faktur, dan jadwal pengiriman lebih awal.",
      ],
      localCases: [
        ["Rumah / ruko panas", "Cek ukuran ruang, daya listrik, dan posisi outdoor dulu sebelum pilih PK."],
        ["Toko & kantor", "Butuh dingin stabil saat jam ramai; stok dan jadwal bisa dikonfirmasi via WhatsApp."],
        ["Proyek / banyak unit", "Spesifikasi bisa diseragamkan, dengan faktur dan jadwal pengiriman bertahap."],
      ],
      label: "Toko AC Cilacap",
      title: "Toko AC Cilacap — Dealer Resmi, Kirim & Pasang dari Banyumas | Radja AC",
      description:
        "Toko AC Cilacap: unit AC original dari dealer resmi & Gree Proshop, dikirim dan dipasang dari showroom Banyumas. Cek PK, stok, dan harga untuk rumah, ruko, kantor, atau proyek lewat WhatsApp.",
      h1: "Toko AC Cilacap untuk Rumah, Ruko, Kantor & Banyak Unit",
      eyebrow: "Layanan AC Area Cilacap",
      intro:
        "Cari toko AC Cilacap yang bisa dipercaya? Radja AC dealer resmi yang melayani seluruh Cilacap dari showroom Banyumas — mulai dari jenis ruangnya: rumah, ruko, toko, kantor, atau pengadaan banyak unit. Dari situ kami arahkan kapasitas yang pas, bandingkan brand original sesuai budget, lalu atur pengiriman dan pemasangannya.",
      localContext:
        "Kebutuhan AC di Cilacap terbelah dua: pemakaian harian rumah dan ruko yang gampang panas, plus pengadaan banyak unit untuk kantor dan proyek. Tambahan lagi, udara pantainya bikin unit luar lebih rentan korosi, jadi penempatannya ikut menentukan umur AC.",
      coverageNote:
        "Sebagai dealer resmi yang melayani seluruh Cilacap, Radja AC jadi alternatif praktis dari sekadar cari toko AC terdekat — kebutuhan AC Cilacap dilayani dari basis showroom dan gudang di Banyumas. Stok, pengiriman, dan opsi pemasangan dikonfirmasi setelah alamat, jumlah unit, dan kondisi ruangan jelas.",
      commonNeeds: [
        "AC rumah tinggal, kamar tidur, dan ruang keluarga di Cilacap",
        "AC toko, ruko, kantor, klinik, dan ruang usaha",
        "AC untuk beberapa ruangan, banyak titik, atau bangunan usaha",
        "Pengadaan unit untuk usaha, kantor, proyek, dan kebutuhan banyak unit",
      ],
      buyingChecks: [
        "Kecamatan atau area detail pengiriman di Cilacap",
        "Ukuran ruangan, tinggi plafon, dan jumlah unit yang dibutuhkan",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Kebutuhan unit saja, pengiriman, atau opsi pemasangan sesuai alamat",
      ],
      paymentNote:
        "Pembayaran dibahas setelah kebutuhan jelas: DP, COD, transfer, atau termin untuk pengadaan proyek.",
      relatedLinks: [
        ["Jual AC Kroya", routes.jualAcKroya],
        ["Jual AC Majenang", routes.jualAcMajenang],
        ["Jual AC Sidareja", routes.jualAcSidareja],
        ["Jual AC Kesugihan", routes.jualAcKesugihan],
        ["Jual AC Adipala", routes.jualAcAdipala],
        ["Jual AC Purwokerto", routes.jualAcPurwokerto],
        ["Jual AC Banyumas", routes.jualAcBanyumas],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Kantor & Komersial", routes.katalogAcKantorKomersial],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["Pengadaan AC Proyek", routes.pengadaanAc],
        ["AC Daikin", routes.brandDaikin],
        ["AC Gree", routes.brandGree],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Tentang Radja AC", routes.tentangKami],
        ["Kontak Radja AC", routes.kontak],
        ["Memilih AC untuk Daerah Pesisir", routes.artikelMemilihAcUntukDaerahPesisir],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Cilacap",
      waIntent: "cek stok dan estimasi AC Cilacap dengan data kecamatan ukuran ruangan daya listrik jumlah unit alamat dan kebutuhan pemasangan",
      waArea: "Cilacap",
      keywordVariants: [
        "toko AC Cilacap",
        "AC Cilacap",
        "harga AC Cilacap",
        "beli AC Cilacap",
        "AC kantor Cilacap",
        "AC proyek industri Cilacap",
        "pengadaan AC pabrik Cilacap",
        "AC pesisir tahan korosi Cilacap",
        "AC rumah Cilacap",
        "pasang AC Cilacap",
        "AC banyak unit Cilacap",
        "jual AC Cilacap",
        "dealer AC Cilacap",
        "dealer AC terdekat Cilacap",
      ],
      nearbyAreaLinks: [
        ["Kroya", routes.jualAcKroya],
        ["Majenang", routes.jualAcMajenang],
        ["Sidareja", routes.jualAcSidareja],
        ["Kesugihan", routes.jualAcKesugihan],
        ["Adipala", routes.jualAcAdipala],
      ],
      trustBullets: [
        "Showroom dan gudang kami ada di Banyumas; unit dipastikan ready sebelum dikirim ke Cilacap.",
        "Kapasitas PK kami hitung dari luas ruang, daya listrik, jumlah unit, dan kondisi lokasimu.",
        "Aktivitas kami nyata dan terdokumentasi: stok fisik, proses pengiriman, sampai pemasangan.",
      ],
      localFaq: [
        [
          "Bisa kirim AC ke Cilacap kota, Kroya, Majenang, atau Sidareja?",
          "Bisa, semua kecamatan Cilacap kami layani. Sebutkan kecamatan, alamat, jumlah unit, dan kebutuhan pasangnya — dari situ stok dan jadwal pengiriman kami susun.",
        ],
        [
          "Bisa sekalian pasang AC di Cilacap?",
          "Tentu, tinggal bilang ke kami. Foto titik indoor dan outdoor bikin tim lebih gampang memperkirakan posisi pasang, jalur pipa, dan material tambahannya.",
        ],
        [
          "Karena Cilacap dekat laut, outdoor AC cepat karat?",
          "Udara pesisir memang lebih berat buat unit outdoor. Posisikan outdoor supaya nggak langsung kena angin laut, dan rutin dirawat biar umurnya panjang.",
        ],
        [
          "Rumah di Cilacap daya listriknya pas-pasan, harus low watt?",
          "Kalau daya rumahmu 900–1300 watt, low watt paling aman biar MCB nggak sering turun. Sebutkan daya listrik dan ukuran kamarnya, nanti kami arahkan tipe yang cocok.",
        ],
        [
          "Bisa pengadaan AC banyak unit untuk kantor atau proyek?",
          "Ini justru yang sering kami tangani. Sebutkan jumlah ruang, target waktu, dan kebutuhan faktur — stok, spesifikasi, jadwal, sampai pembayaran kami bahas sebelum pengiriman.",
        ],
      ],
    },
  {
      slug: "jual-ac-kroya",
      path: routes.jualAcKroya,
      areaName: "Kroya",
      localLandmarks: [
        "Stasiun Kroya (simpul kereta jalur selatan Jawa)",
        "Pasar Kroya dan deretan ruko di jalan utama",
        "Pertigaan Buntu–Kroya–Cilacap (jalur lintas selatan)",
        "Kawasan kos dan hunian sekitar stasiun",
        "Pabrik dan gudang di koridor industri Kroya–Cilacap",
      ],
      localBenefits: [
        "Toko dan ruko di sekitar Stasiun dan Pasar Kroya yang ramai penumpang dan pembeli cepat gerah saat siang, sehingga AC ruang jualan jadi kebutuhan nyata bukan sekadar kenyamanan",
        "Kos dan hunian di sekitar stasiun banyak dihuni pekerja dan penumpang transit yang butuh kamar adem; low watt jadi pilihan agar daya per kamar aman",
        "Pabrik dan gudang di koridor Kroya–Cilacap kadang butuh pengadaan beberapa unit untuk ruang kerja dan kantor lapangan dengan jadwal yang mengikuti operasional",
      ],
      localCases: [
        ["Toko & ruko sekitar stasiun", "Kapasitas dihitung dari luas dan lalu lalang penumpang; sedikit lebih besar dari kamar tidur biasa."],
        ["Kos & hunian transit", "Low watt tipe seragam jaga daya total bangunan saat banyak unit menyala serentak."],
        ["Kantor & gudang industri", "Pengadaan beberapa unit dengan jadwal yang mengikuti operasional; bisa dilengkapi faktur."],
      ],
      label: "Jual AC Kroya",
      title: "Jual AC Kroya | Toko Sekitar Stasiun, Kos Transit & Koridor Industri Cilacap — Radja AC",
      description:
        "AC untuk toko dan ruko sekitar Stasiun Kroya, kos pekerja transit, atau kantor di koridor industri Kroya–Cilacap? Radja AC cek PK, stok, dan pengiriman via WhatsApp.",
      h1: "Jual AC Kroya untuk Rumah, Toko & Usaha",
      eyebrow: "Area Cilacap",
      intro:
        "Kroya simpul transit jalur selatan Jawa — toko dan ruko ramai penumpang, kos dan hunian dekat stasiun, plus koridor industri ke arah Cilacap. Kasih tahu jenis ruang dan alamatmu, Radja AC cocokkan PK, stok, dan jadwal pengiriman dari situ.",
      localContext:
        "Kroya adalah simpul transit penting di jalur selatan Jawa—Stasiun Kroya melayani kereta lintas Jawa sehingga denyut ekonominya campuran antara dagang dan transit. Toko dan ruko di sekitar Pasar Kroya dan stasiun ramai penumpang dan pembeli, cepat gerah saat siang karena pintu sering terbuka. Kos dan hunian di sekitar stasiun banyak dihuni pekerja dan penumpang transit yang butuh kamar adem. Di koridor Kroya–Cilacap juga ada pabrik dan gudang yang kadang butuh pengadaan beberapa unit untuk ruang kerja.",
      coverageNote:
        "Showroom dan gudang Radja AC ada di Banyumas, dan Kroya terhubung lewat jalur lintas selatan (Buntu–Kroya). Stok, pengiriman ke alamat sekitar stasiun, Pasar Kroya, atau koridor industri Kroya–Cilacap, sampai opsi pemasangan dikonfirmasi setelah alamat, jumlah unit, dan kondisi ruang jelas.",
      keywordVariants: [
        "toko AC Kroya",
        "AC Kroya",
        "AC rumah Kroya",
        "AC toko dan ruko Kroya",
        "AC kantor kecil Kroya",
        "AC usaha Kroya",
        "banyak unit area Kroya",
        "cek PK AC Kroya",
      ],
      nearbyAreaLinks: [
        ["Cilacap", routes.jualAcCilacap],
        ["Kesugihan", routes.jualAcKesugihan],
        ["Adipala", routes.jualAcAdipala],
        ["Sidareja", routes.jualAcSidareja],
        ["Banyumas", routes.jualAcBanyumas],
      ],
      trustBullets: [
        "Toko dan ruko sekitar stasiun: kapasitas dihitung dari luas dan lalu lalang, bukan sekadar ukuran kamar.",
        "Kos multi-kamar: low watt tipe seragam jaga daya total bangunan dan permudah perawatan antar kamar.",
        "Koridor Kroya–Cilacap: pengadaan beberapa unit bisa dengan jadwal dan faktur yang disusun dari awal.",
      ],
      localFaq: [
        [
          "AC untuk toko atau ruko di sekitar Stasiun Kroya yang ramai penumpang, pilih apa?",
          "Ruang yang ramai penumpang dan pintunya sering terbuka butuh kapasitas sedikit lebih besar dari kamar biasa agar dingin merata. Sebutkan ukuran toko dan jam ramai untuk cek unit dan stok.",
        ],
        [
          "Kos di sekitar Stasiun Kroya banyak penghuni, AC-nya bagaimana?",
          "Kos yang banyak kamarnya sebaiknya pakai low watt tipe seragam agar daya total bangunan tidak turun saat banyak unit menyala. Sebutkan jumlah kamar dan daya listrik total untuk arahan.",
        ],
        [
          "Bisa pengadaan beberapa unit untuk kantor atau gudang di koridor Kroya–Cilacap?",
          "Bisa. Sebutkan jumlah ruang, ukuran, dan target waktu; unit disiapkan dari stok lalu pengiriman dan pemasangan dijadwalkan mengikuti operasional. Pembayaran bisa DP atau transfer.",
        ],
        [
          "Bisa kirim dan pasang AC ke alamat di Kroya atau sekitar pertigaan Buntu?",
          "Langsung kirimkan alamat dan jumlah unitnya. Unit dikirim ke alamat di Kroya lalu pemasangan dijadwalkan sesuai akses lokasi untuk perkiraan pengiriman.",
        ],
      ],
      commonNeeds: [
        "AC rumah dan kamar kos di sekitar Stasiun Kroya",
        "AC toko dan ruko di sekitar Pasar Kroya yang ramai penumpang",
        "AC kantor kecil dan ruang kerja di koridor industri Kroya–Cilacap",
        "Pengadaan beberapa unit untuk kos transit, kantor, atau gudang",
      ],
      buyingChecks: [
        "Alamat detail area Kroya (sekitar stasiun, Pasar Kroya, atau koridor industri)",
        "Ukuran ruang dan lalu lalang penumpang untuk perkiraan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Jumlah unit dan jadwal pengiriman yang mengikuti operasional",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["Memilih AC untuk Daerah Pesisir", routes.artikelMemilihAcUntukDaerahPesisir],
        ["AC Inverter", routes.katalogAcInverter],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Kroya",
      waIntent: "cek stok AC Kroya dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Kroya",
    },
  {
      slug: "jual-ac-majenang",
      path: routes.jualAcMajenang,
      areaName: "Majenang",
      localLandmarks: [
        "Pasar Majenang dan deretan ruko di jalan utama",
        "Terminal Majenang dan jalur menuju Banjar/Bandung",
        "RSUD Majenang (rumah sakit umum daerah)",
        "Kawasan kos dan hunian sekitar pusat kota",
        "Jalur Majenang–Sidareja–Cilacap (lintas barat)",
      ],
      localBenefits: [
        "Ruko dan toko di Pasar Majenang yang jadi pusat dagang Cilacap barat ramai pembeli dari berbagai kecamatan, sehingga ruang jualan yang adem jadi daya tarik tersendiri",
        "RSUD Majenang dan klinik sekitarnya butuh ruang tunggu dan ruang periksa yang adem sepanjang jam operasional, bukan hanya saat ramai",
        "Majenang adalah titik terjauh dari gudang Banyumas di jalur barat, sehingga pengiriman dijadwalkan tersendiri dan pembeli perlu konfirmasi alamat detail lebih awal",
      ],
      localCases: [
        ["Ruko & toko Pasar Majenang", "AC ruang jualan di pusat dagang Cilacap barat agar pembeli dari berbagai kecamatan betah."],
        ["RSUD & klinik", "AC ruang tunggu dan ruang periksa yang dipakai seharian dengan kapasitas sesuai luas."],
        ["Rumah & kos", "Pemasangan AC kamar dengan pengiriman yang dijadwalkan tersendiri ke Cilacap barat."],
      ],
      label: "Jual AC Majenang",
      title: "Jual AC Majenang | Pasar Dagang Cilacap Barat, RSUD & Rumah — Radja AC",
      description:
        "AC untuk ruko di Pasar Majenang pusat dagang Cilacap barat, ruang tunggu RSUD Majenang, atau rumah? Radja AC bantu pilih unit, konfirmasi stok, dan jadwalkan pengiriman ke Cilacap barat.",
      h1: "Jual AC Majenang untuk Rumah, Toko & Banyak Unit",
      eyebrow: "Area Cilacap Barat",
      intro:
        "Majenang pusat dagang Cilacap barat — ruko dan toko di Pasar Majenang ramai pembeli dari berbagai kecamatan, RSUD dan klinik yang sibuk sepanjang jam layanan, plus jalur lintas ke Banjar dan Bandung. Karena Majenang titik terjauh dari gudang Radja AC di Banyumas, sebutkan jenis ruang dan alamat detailmu — kami cocokkan PK, stok brand original, dan jadwal pengiriman dari situ.",
      localContext:
        "Majenang adalah kota dagang terbesar di Cilacap bagian barat, di jalur lintas menuju Banjar dan Bandung, dengan Pasar Majenang sebagai pusat ekonomi yang menarik pembeli dari berbagai kecamatan sekitarnya. RSUD Majenang dan klinik di sekitarnya juga jadi pusat layanan kesehatan untuk wilayah barat. Karena posisinya paling jauh dari gudang Radja AC di Banyumas di antara area Cilacap, pengiriman ke Majenang dijadwalkan tersendiri dan pembeli perlu konfirmasi alamat detail lebih awal. Untuk jual AC Majenang, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, transfer, atau COD setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC ada di Banyumas, dan Majenang jadi titik terjauh di jalur barat (arah Banjar–Bandung). Karena itu pengiriman ke Pasar Majenang, RSUD, atau alamat sekitar dijadwalkan tersendiri — stok, jadwal, dan opsi pemasangan dikonfirmasi setelah alamat detail dan jumlah unit jelas.",
      keywordVariants: [
        "toko AC Majenang",
        "AC Majenang",
        "AC rumah Majenang",
        "AC toko dan ruko Majenang",
        "AC kantor kecil Majenang",
        "AC usaha Majenang",
        "banyak unit area Majenang",
        "cek PK AC Majenang",
      ],
      nearbyAreaLinks: [
        ["Cilacap", routes.jualAcCilacap],
        ["Sidareja", routes.jualAcSidareja],
        ["Kroya", routes.jualAcKroya],
        ["Banyumas", routes.jualAcBanyumas],
        ["Kebumen", routes.jualAcKebumen],
      ],
      trustBullets: [
        "Ruko dan toko Pasar Majenang: kapasitas dihitung dari luas dan lalu lalang pembeli dari berbagai kecamatan, bukan sekadar ukuran kamar.",
        "RSUD dan klinik: ruang tunggu dan ruang periksa dipakai sepanjang jam layanan, jadi kapasitas dipilih agar stabil, bukan yang termurah.",
        "Jalur barat terjauh dari gudang Banyumas: pengiriman dan pemasangan dijadwalkan tersendiri, faktur dan jumlah unit disusun dari awal.",
      ],
      localFaq: [
        [
          "AC untuk ruko atau toko di Pasar Majenang yang jadi pusat dagang Cilacap barat?",
          "Ruang jualan yang ramai pembeli dari berbagai kecamatan dan pintunya sering terbuka butuh kapasitas sesuai luas dan lalu lalang. Sebutkan ukuran ruko dan jam buka untuk cek unit dan stok.",
        ],
        [
          "AC untuk ruang tunggu atau ruang periksa di RSUD atau klinik Majenang?",
          "Ruang layanan kesehatan yang dipakai seharian butuh kapasitas yang stabil, bukan yang termurah. Sebutkan ukuran ruang dan jam operasional untuk perkiraan PK dan stok.",
        ],
        [
          "Majenang paling jauh dari gudang Banyumas, pengirimannya bagaimana?",
          "Pengiriman ke Majenang dijadwalkan tersendiri karena jaraknya dari gudang Banyumas. Konfirmasi alamat detail dan jumlah unit lebih awal agar jadwal pengiriman dan pemasangan bisa disusun.",
        ],
        [
          "AC rumah di Majenang, pilih low watt atau inverter?",
          "Low watt cocok untuk rumah dengan daya 900–1300 watt agar MCB tidak turun; inverter lebih hemat untuk kamar yang AC-nya menyala hampir setiap malam. Sebutkan daya dan ukuran kamar untuk arahan yang lebih tepat.",
        ],
      ],
      commonNeeds: [
        "AC ruko dan toko di Pasar Majenang, pusat dagang Cilacap barat",
        "AC ruang tunggu dan ruang periksa RSUD atau klinik Majenang",
        "AC rumah dan kos di sekitar pusat kota Majenang",
        "Pengadaan beberapa unit dengan faktur dan jadwal ke jalur barat",
      ],
      buyingChecks: [
        "Alamat detail area Majenang (Pasar Majenang, sekitar RSUD, atau permukiman)",
        "Ukuran ruangan dan jam operasional untuk perkiraan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Jumlah unit dan konfirmasi alamat lebih awal untuk jadwal pengiriman",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["AC Kantor & Komersial", routes.katalogAcKantorKomersial],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Majenang",
      waIntent: "cek stok AC Majenang dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Majenang",
    },
  {
      slug: "jual-ac-sidareja",
      path: routes.jualAcSidareja,
      areaName: "Sidareja",
      localLandmarks: [
        "Stasiun Sidareja dan jalur kereta selatan",
        "Pasar Sidareja dan ruko di jalan utama kecamatan",
        "Kawasan rawa dan pertanian Sidareja (Rawa Besar)",
        "Jalur Sidareja–Majenang (lintas barat Cilacap)",
        "Permukiman warga di sekitar pasar dan stasiun",
      ],
      localBenefits: [
        "Ruko dan toko di sekitar Pasar Sidareja yang jadi titik belanja warga beberapa desa sekitar butuh ruang yang adem agar pembeli betah, terutama saat hari pasar ramai",
        "Rumah di permukiman sekitar rawa Sidareja terasa lembap dan gerah saat siang, sehingga AC kamar jadi kebutuhan yang lebih terasa dibanding daerah yang lebih kering",
        "Sidareja berada di antara Majenang dan Cilacap kota, sehingga pengiriman unit dijadwalkan tersendiri dan pembeli perlu konfirmasi alamat lebih awal",
      ],
      localCases: [
        ["Ruko & toko hari pasar", "AC ruang jualan di Pasar Sidareja agar pembeli dari desa sekitar betah saat hari pasar ramai."],
        ["Rumah sekitar rawa", "Pemasangan AC kamar yang terasa lembap dan gerah karena pengaruh rawa di sekitar permukiman."],
        ["Kantor & usaha", "Pemilihan unit ruang kerja dengan pengiriman yang dijadwalkan ke jalur barat Cilacap."],
      ],
      label: "Jual AC Sidareja",
      title: "Jual AC Sidareja | Ruko Pasar, Rumah Sekitar Rawa Besar & Jalur Barat Cilacap — Radja AC",
      description:
        "AC untuk ruko di Pasar Sidareja, rumah yang lembap karena Rawa Besar, atau usaha jalur barat Cilacap? Radja AC rekomendasikan PK sesuai kondisi lembap dan atur pengiriman ke Sidareja.",
      h1: "Jual AC Sidareja untuk Rumah, Ruko & Usaha",
      eyebrow: "Area Cilacap Barat",
      intro:
        "Sidareja dikelilingi kawasan rawa termasuk Rawa Besar, jadi rumah di permukiman sekitar terasa lebih lembap dan gerah saat siang. Ruko dan toko di Pasar Sidareja ramai pembeli dari desa-desa sekitar saat hari pasar, sementara posisinya di jalur barat antara Majenang dan Cilacap kota bikin pengiriman dijadwalkan tersendiri. Sebutkan jenis ruang dan alamat detailmu — Radja AC cocokkan PK sesuai kondisi lembap, stok brand original, dan jadwal pengirimannya dari situ.",
      localContext:
        "Sidareja adalah kota kecamatan di Cilacap bagian barat yang dikelilingi kawasan rawa dan pertanian—termasuk Rawa Besar—dengan Stasiun Sidareja dan Pasar Sidareja sebagai pusat kegiatan. Karena dikelilingi rawa, udara di permukiman sekitar terasa lebih lembap dan gerah saat siang dibanding daerah yang lebih kering, sehingga AC kamar jadi kebutuhan yang lebih terasa. Ruko dan toko di sekitar pasar ramai saat hari pasar karena pembeli datang dari beberapa desa sekitar. Posisi Sidareja di antara Majenang dan Cilacap kota membuat pengiriman dijadwalkan tersendiri. Untuk jual AC Sidareja, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC ada di Banyumas, dan Sidareja berada di jalur barat di antara Majenang dan Cilacap kota. Pengiriman ke alamat sekitar Pasar Sidareja atau permukiman dekat rawa dijadwalkan tersendiri — stok, jadwal, dan opsi pemasangan dikonfirmasi setelah alamat dan jumlah unit jelas.",
      keywordVariants: [
        "toko AC Sidareja",
        "AC Sidareja",
        "AC rumah Sidareja",
        "AC toko dan ruko Sidareja",
        "AC kantor kecil Sidareja",
        "AC usaha Sidareja",
        "banyak unit area Sidareja",
        "cek PK AC Sidareja",
      ],
      nearbyAreaLinks: [
        ["Cilacap", routes.jualAcCilacap],
        ["Majenang", routes.jualAcMajenang],
        ["Kroya", routes.jualAcKroya],
        ["Kesugihan", routes.jualAcKesugihan],
        ["Kebumen", routes.jualAcKebumen],
      ],
      trustBullets: [
        "Rumah sekitar rawa (Rawa Besar): kapasitas PK dihitung dari luas dan kondisi udara lembap, bukan sekadar ukuran standar.",
        "Ruko dan toko Pasar Sidareja: kapasitas disesuaikan dengan luas dan jumlah pengunjung puncak saat hari pasar, bukan ukuran kamar biasa.",
        "Jalur barat di antara Majenang dan Cilacap kota: pengiriman dan pemasangan dijadwalkan tersendiri, jumlah unit dikonfirmasi dari awal.",
      ],
      localFaq: [
        [
          "Rumah di Sidareja dekat rawa terasa lembap dan gerah, AC apa yang cocok?",
          "Udara lembap dari rawa membuat ruangan terasa lebih gerah, jadi kapasitas PK perlu dihitung dari luas dan kondisi lembap tersebut, bukan sekadar ukuran standar. Sebutkan ukuran kamar dan kondisi sekitar untuk arahan yang lebih tepat.",
        ],
        [
          "AC untuk ruko atau toko di Pasar Sidareja saat hari pasar ramai?",
          "Hari pasar membuat toko lebih ramai dari biasanya; kapasitas dihitung dari luas dan jumlah pengunjung puncak. Sebutkan ukuran toko dan hari pasar untuk cek unit dan stok.",
        ],
        [
          "Sidareja di antara Majenang dan Cilacap kota, pengirimannya bagaimana?",
          "Pengiriman ke Sidareja dijadwalkan tersendiri karena posisinya di jalur barat. Konfirmasi alamat detail dan jumlah unit lebih awal agar jadwal pengiriman dan pemasangan bisa disusun.",
        ],
        [
          "AC rumah di Sidareja, daya listrik terbatas, pilih apa?",
          "Rumah dengan daya 900–1300 watt banyak pakai low watt agar MCB tidak turun. Sebutkan daya dan ukuran kamar untuk cek unit dan stok yang sesuai.",
        ],
      ],
      commonNeeds: [
        "AC rumah di permukiman sekitar rawa yang terasa lembap dan gerah",
        "AC ruko dan toko di Pasar Sidareja yang ramai saat hari pasar",
        "AC kantor kecil dan ruang usaha di sekitar pusat kecamatan",
        "Pembelian beberapa unit untuk usaha lokal dengan jadwal ke jalur barat",
      ],
      buyingChecks: [
        "Alamat detail area Sidareja (sekitar Pasar Sidareja, stasiun, atau dekat rawa)",
        "Ukuran ruangan dan kondisi lembap sekitar untuk perkiraan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Jumlah unit dan konfirmasi alamat lebih awal untuk jadwal pengiriman",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Split Rumah", routes.katalogAcSplitRumah],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Sidareja",
      waIntent: "cek stok AC Sidareja dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Sidareja",
    },
  {
      slug: "jual-ac-kesugihan",
      path: routes.jualAcKesugihan,
      areaName: "Kesugihan",
      localLandmarks: [
        "Pondok Pesantren Al-Ihya Ulumaddin (Kesugihan)",
        "Kawasan industri Cilacap (koridor Kesugihan–Cilacap kota)",
        "Asrama santri dan kos sekitar pesantren",
        "Pasar Kesugihan dan permukiman warga",
        "Jalur Kesugihan–Cilacap kota (jalan nasional)",
      ],
      localBenefits: [
        "Pondok Pesantren Al-Ihya Ulumaddin punya ratusan santri dengan asrama dan ruang belajar; ruang kelas dan aula yang dipakai seharian butuh pendinginan yang berbeda dari kamar kos biasa",
        "Asrama dan kos santri dengan banyak kamar kecil cari AC low watt tipe seragam agar daya total bangunan tidak turun dan perawatan antar kamar lebih mudah",
        "Kantor dan usaha di koridor Kesugihan–Cilacap yang dekat kawasan industri butuh unit yang cepat dingin dan tahan dipakai seharian di udara panas",
      ],
      localCases: [
        ["Ruang kelas & aula pesantren", "AC ruang belajar dan aula Al-Ihya Ulumaddin yang dipakai seharian; kapasitas dihitung dari luas dan jumlah santri."],
        ["Asrama & kos santri", "AC banyak kamar kecil dengan low watt tipe seragam agar daya total bangunan aman dan perawatan mudah."],
        ["Kantor & usaha koridor industri", "Pemilihan unit ruang kerja di jalur Kesugihan–Cilacap yang dekat kawasan industri."],
      ],
      label: "Jual AC Kesugihan",
      title: "Jual AC Kesugihan | Pesantren Al-Ihya Ulumaddin, Asrama Santri & Industri — Radja AC",
      description:
        "AC ruang kelas dan asrama Pesantren Al-Ihya Ulumaddin Kesugihan, atau kantor di koridor industri Cilacap? Radja AC cek PK, stok, dan pengiriman via WhatsApp.",
      h1: "Jual AC Kesugihan untuk Rumah, Kantor & Proyek",
      eyebrow: "Area Cilacap",
      intro:
        "Kesugihan dikenal dengan Pondok Pesantren Al-Ihya Ulumaddin — ratusan santri dengan asrama, ruang kelas, dan aula yang dipakai seharian, plus koridor industri Kesugihan–Cilacap di dekatnya. Kebutuhan AC-nya beragam: ruang kelas dan aula butuh kapasitas sesuai jumlah santri, asrama dan kos cocok low watt tipe seragam, sedangkan kantor dan usaha butuh unit yang cepat dingin. Sebutkan jenis ruang dan alamat detailmu — Radja AC cocokkan PK, stok brand original, dan jadwal pengirimannya dari situ.",
      localContext:
        "Kesugihan berada di jalur Cilacap menuju kota, dikenal dengan Pondok Pesantren Al-Ihya Ulumaddin—salah satu pesantren besar di Cilacap—yang punya ratusan santri dengan asrama, ruang kelas, dan aula. Kebutuhan AC di sini beragam: ruang kelas dan aula yang dipakai seharian butuh kapasitas yang dihitung dari luas dan jumlah santri, sedangkan asrama dan kos santri butuh unit low watt tipe seragam agar daya total bangunan tidak turun. Di sisi lain, kantor dan usaha di koridor Kesugihan–Cilacap yang dekat kawasan industri butuh unit yang cepat dingin. Untuk jual AC Kesugihan, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, transfer, atau COD setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC ada di Banyumas, dan Kesugihan terhubung lewat jalan nasional Kesugihan–Cilacap kota. Pengiriman ke alamat sekitar pesantren, asrama, atau koridor industri dikonfirmasi setelah alamat, jumlah unit, dan kondisi ruang jelas — termasuk untuk pengadaan banyak unit yang dijadwalkan bertahap.",
      keywordVariants: [
        "toko AC Kesugihan",
        "AC Kesugihan",
        "AC rumah Kesugihan",
        "AC asrama dan kos santri Kesugihan",
        "AC kantor kecil Kesugihan",
        "AC ruang usaha Kesugihan",
        "banyak unit area Kesugihan",
        "cek PK AC Kesugihan",
      ],
      nearbyAreaLinks: [
        ["Cilacap", routes.jualAcCilacap],
        ["Kroya", routes.jualAcKroya],
        ["Adipala", routes.jualAcAdipala],
        ["Sidareja", routes.jualAcSidareja],
        ["Banyumas", routes.jualAcBanyumas],
      ],
      trustBullets: [
        "Ruang kelas dan aula Al-Ihya Ulumaddin: kapasitas dihitung dari luas dan jumlah santri, bukan sekadar ukuran kamar.",
        "Asrama dan kos santri: low watt tipe seragam menjaga daya total bangunan dan permudah perawatan antar kamar.",
        "Koridor industri Kesugihan–Cilacap: pengadaan beberapa unit bisa dengan jadwal dan faktur yang disusun dari awal.",
      ],
      localFaq: [
        [
          "AC untuk ruang kelas atau aula di Pesantren Al-Ihya Ulumaddin Kesugihan, pilih apa?",
          "Ruang kelas dan aula yang dipakai seharian dengan banyak santri butuh kapasitas yang dihitung dari luas dan jumlah orang, bukan sekadar ukuran kamar biasa. Sebutkan ukuran ruang dan jumlah santri untuk perkiraan PK dan stok.",
        ],
        [
          "AC untuk asrama atau kos santri banyak kamar di Kesugihan, hemat listrik?",
          "Untuk banyak kamar kecil, low watt tipe seragam menjaga daya total bangunan dan memudahkan perawatan antar kamar. Sebutkan jumlah kamar dan daya listrik total untuk cek unit dan stok.",
        ],
        [
          "Bisa pengadaan beberapa unit untuk kantor atau usaha di koridor Kesugihan–Cilacap?",
          "Bisa. Sebutkan jumlah ruang, ukuran, dan target waktu; unit disiapkan dari stok lalu pengiriman dan pemasangan dijadwalkan. Pembayaran bisa DP atau transfer.",
        ],
        [
          "Bisa kirim dan pasang AC ke alamat di Kesugihan atau sekitar pesantren?",
          "Bisa. Unit dikirim ke alamat di Kesugihan lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat detail dan jumlah unit untuk perkiraan pengiriman.",
        ],
      ],
      commonNeeds: [
        "AC ruang kelas dan aula di Pesantren Al-Ihya Ulumaddin",
        "AC asrama dan kos santri dengan banyak kamar kecil",
        "AC kantor dan ruang usaha di koridor Kesugihan–Cilacap",
        "Pengadaan beberapa unit untuk pesantren, kantor, atau proyek kecil",
      ],
      buyingChecks: [
        "Alamat detail area Kesugihan (sekitar pesantren, asrama, atau koridor industri)",
        "Ukuran ruang dan jumlah santri atau penghuni untuk perkiraan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Jumlah unit dan jadwal pengadaan yang bisa bertahap",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Kantor & Komersial", routes.katalogAcKantorKomersial],
        ["Pengadaan AC Proyek", routes.pengadaanAc],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Kesugihan",
      waIntent: "cek stok AC Kesugihan dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Kesugihan",
    },
  {
      slug: "jual-ac-adipala",
      path: routes.jualAcAdipala,
      areaName: "Adipala",
      localLandmarks: [
        "PLTU Adipala (Pembangkit Listrik Tenaga Uap)",
        "Pantai Widarapayung dan Pantai Jetis (pesisir selatan Adipala)",
        "Pasar Adipala dan permukiman nelayan",
        "Kawasan tambak dan pertanian pesisir",
        "Jalur Adipala–Kroya–Cilacap kota",
      ],
      localBenefits: [
        "Kontraktor, vendor, dan kantor lapangan di sekitar PLTU Adipala kadang butuh pengadaan beberapa unit AC untuk ruang kerja dan mess dengan spesifikasi yang bisa dilengkapi faktur",
        "Rumah dan toko di permukiman pesisir Adipala yang panas dan lembap butuh AC yang cepat mendinginkan ruangan; udara asin dari laut membuat penempatan outdoor perlu diperhatikan agar tidak cepat berkarat",
        "Nelayan dan pelaku usaha tambak yang membangun rumah atau warung di pesisir Adipala sering cari unit yang tahan dipakai di lingkungan lembap dengan perawatan yang tidak rumit",
      ],
      localCases: [
        ["Kantor & mess sekitar PLTU", "Pengadaan AC ruang kerja dan mess untuk kontraktor atau vendor proyek pembangkit, bisa dilengkapi faktur."],
        ["Rumah & warung nelayan pesisir", "AC kamar dan ruang usaha di permukiman nelayan Adipala; penempatan outdoor diperhatikan karena udara asin."],
        ["Toko & usaha jalur Adipala–Kroya", "AC ruang jualan di jalur utama agar pembeli betah di cuaca panas pesisir."],
      ],
      label: "Jual AC Adipala",
      title: "Jual AC Adipala | PLTU, Nelayan Pantai Widarapayung & Toko Pesisir — Radja AC",
      description:
        "AC untuk mess kontraktor PLTU Adipala, rumah nelayan di Pantai Widarapayung, atau toko pesisir yang panas? Radja AC cek PK, stok, dan pengiriman via WhatsApp.",
      h1: "Jual AC Adipala untuk Rumah, Toko & Usaha",
      eyebrow: "Area Cilacap",
      intro:
        "Adipala kecamatan pesisir Cilacap — ada PLTU Adipala dengan kontraktor dan mess yang kadang butuh pengadaan banyak unit, permukiman nelayan di sekitar Pantai Widarapayung dan Jetis, plus toko di jalur Adipala–Kroya yang panas. Karena dekat laut, udara asin bikin penempatan outdoor perlu diperhatikan biar tidak cepat berkarat. Sebutkan jenis ruang dan alamat detailmu — Radja AC cocokkan PK, stok brand original, dan jadwal pengirimannya dari situ.",
      localContext:
        "Adipala adalah kecamatan pesisir di Cilacap yang dikenal dengan PLTU Adipala—pembangkit listrik tenaga uap yang jadi salah satu infrastruktur energi penting di Jawa Tengah—serta pantai selatan seperti Pantai Widarapayung dan Pantai Jetis. Permukiman nelayan dan pelaku usaha tambak tersebar di sepanjang pesisir, dengan udara panas dan lembap yang membuat ruangan cepat gerah. Kontraktor dan vendor sekitar PLTU kadang butuh pengadaan beberapa unit AC untuk ruang kerja dan mess. Karena dekat laut, udara asin mempercepat korosi pada unit outdoor sehingga penempatan perlu diperhatikan sejak awal. Untuk jual AC Adipala, unit dikirim ke alamat lalu dipasang, dengan pembayaran DP, COD, atau transfer setelah stok dipastikan.",
      coverageNote:
        "Showroom dan gudang Radja AC ada di Banyumas, dan Adipala dijangkau lewat jalur Adipala–Kroya–Cilacap kota. Pengiriman ke alamat di permukiman pesisir, sekitar PLTU, atau jalur utama dikonfirmasi setelah alamat, jumlah unit, dan kondisi ruang jelas — termasuk pengadaan beberapa unit yang bisa dilengkapi faktur.",
      keywordVariants: [
        "toko AC Adipala",
        "AC Adipala",
        "AC rumah Adipala",
        "AC toko dan usaha pesisir Adipala",
        "AC kantor kecil Adipala",
        "AC ruangan panas Adipala",
        "banyak unit area Adipala",
        "cek PK AC Adipala",
      ],
      nearbyAreaLinks: [
        ["Cilacap", routes.jualAcCilacap],
        ["Kroya", routes.jualAcKroya],
        ["Kesugihan", routes.jualAcKesugihan],
        ["Sidareja", routes.jualAcSidareja],
        ["Banyumas", routes.jualAcBanyumas],
      ],
      trustBullets: [
        "Kantor dan mess sekitar PLTU Adipala: pengadaan beberapa unit bisa dilengkapi faktur dan jadwal mengikuti operasional proyek.",
        "Permukiman nelayan pesisir: udara asin mempercepat korosi, jadi penempatan outdoor dan perawatan kami perhatikan dari awal.",
        "Toko dan usaha jalur Adipala–Kroya: kapasitas dihitung dari luas dan paparan panas, bukan sekadar ukuran kamar.",
      ],
      localFaq: [
        [
          "Bisa pengadaan AC untuk kantor lapangan atau mess kontraktor di sekitar PLTU Adipala?",
          "Bisa. Untuk pengadaan ruang kerja dan mess, sebutkan jumlah ruang, ukuran, dan target waktu; unit disiapkan dari stok, bisa dilengkapi faktur, lalu pengiriman dan pemasangan dijadwalkan mengikuti operasional proyek.",
        ],
        [
          "Rumah atau warung nelayan di pesisir Adipala, unit outdoor-nya aman dari korosi?",
          "Udara asin dari laut memang mempercepat korosi pada unit outdoor. Penempatan yang terlindung dari angin laut langsung dan perawatan rutin membantu memperpanjang umur unit. Sebutkan lokasi pemasangan untuk masukan lebih spesifik.",
        ],
        [
          "AC untuk toko atau warung di jalur Adipala–Kroya yang panas, pilih apa?",
          "Ruang usaha di jalur pesisir yang panas dan lembap butuh kapasitas sesuai luas dan paparan panas. Sebutkan ukuran ruang dan jam buka untuk cek unit dan stok yang sesuai.",
        ],
        [
          "Bisa kirim dan pasang AC ke permukiman nelayan atau tambak di Adipala?",
          "Bisa. Unit dikirim ke alamat di Adipala lalu pemasangan dijadwalkan sesuai akses lokasi. Sebutkan alamat detail dan jumlah unit untuk perkiraan pengiriman.",
        ],
      ],
      commonNeeds: [
        "AC kantor lapangan dan mess kontraktor sekitar PLTU Adipala",
        "AC rumah dan warung di permukiman nelayan pesisir",
        "AC toko dan ruang usaha di jalur Adipala–Kroya yang panas",
        "Pengadaan beberapa unit dengan faktur untuk proyek atau usaha",
      ],
      buyingChecks: [
        "Alamat detail area Adipala (permukiman pesisir, sekitar PLTU, atau jalur utama)",
        "Ukuran ruangan, paparan panas, dan jarak dari laut untuk perkiraan PK",
        "Daya listrik serta pilihan standard, low watt, atau inverter",
        "Jumlah unit, kebutuhan faktur, dan jadwal pengiriman",
      ],
      relatedLinks: [
        ["Jual AC Cilacap", routes.jualAcCilacap],
        ["Kalkulator PK AC", routes.kalkulatorPkAc],
        ["Pengiriman & Pemasangan", routes.pengirimanPemasangan],
        ["AC Low Watt", routes.katalogAcLowWatt],
        ["AC Inverter", routes.katalogAcInverter],
        ["Bukti Pengiriman & Proyek", routes.buktiPengirimanProyek],
        ["Kontak Radja AC", routes.kontak],
        ["Memilih AC untuk Daerah Pesisir", routes.artikelMemilihAcUntukDaerahPesisir],
      ],
      ctaLabel: "Chat WhatsApp untuk cek AC Adipala",
      waIntent: "cek stok AC Adipala dengan data alamat ukuran ruangan daya listrik jumlah unit dan kebutuhan pemasangan",
      waArea: "Adipala",
    },
];
